export const QUERY_KEYS = {
  GET_CLASS_HASH_TAGS: "GET_HASH_TAGS",
  GET_CLASS_FIELDS: "GET_CLASS_FIELDS",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_TEACHERS: "GET_TEACHERS",
  GET_STUDENTS: "GET_STUDENTS",
  GET_ORGANIZATION_DEPARTMENT_OR_BRANCH: "GET_ORGANIZATION_DEPARTMENT_OR_BRANCH",
  GET_COURSES: "GET_COURSES",
  GET_CLASS_ROOMS: "GET_CLASS_ROOMS",
  GET_COURSES_MINIMAL: "GET_COURSES_MINIMAL",
} as const;
