export const editorClasses = {
  root: "onair-editor",
  toolbar: {
    hr: "onair-editor-toolbar-hr",
    root: "onair-editor-toolbar-root",
    bold: "onair-editor-toolbar-bold",
    code: "onair-editor-toolbar-code",
    undo: "onair-editor-toolbar-undo",
    redo: "onair-editor-toolbar-redo",
    link: "onair-editor-toolbar-link",
    clear: "onair-editor-toolbar-clear",
    image: "onair-editor-toolbar-image",
    italic: "onair-editor-toolbar-italic",
    strike: "onair-editor-toolbar-strike",
    hardbreak: "onair-editor-toolbar-hardbreak",
    unsetlink: "onair-editor-toolbar-unsetlink",
    codeBlock: "onair-editor-toolbar-code__block",
    alignLeft: "onair-editor-toolbar-align__left",
    fullscreen: "onair-editor-toolbar-fullscreen",
    blockquote: "onair-editor-toolbar-blockquote",
    bulletList: "onair-editor-toolbar-bullet__list",
    alignRight: "onair-editor-toolbar-align__right",
    orderedList: "onair-editor-toolbar-ordered__list",
    alignCenter: "onair-editor-toolbar-align__center",
    alignJustify: "onair-editor-toolbar-align__justify",
  },
  content: {
    hr: "onair-editor-content-hr",
    root: "onair-editor-content-root",
    link: "onair-editor-content-link",
    image: "onair-editor-content-image",
    codeInline: "onair-editor-content-code",
    heading: "onair-editor-content-heading",
    listItem: "onair-editor-content-list-item",
    codeBlock: "onair-editor-content-code-block",
    blockquote: "onair-editor-content-blockquote",
    langSelect: "onair-editor-content-lang__select",
    placeholder: "onair-editor-content-placeholder",
    bulletList: "onair-editor-content-bullet__list",
    orderedList: "onair-editor-content-ordered__list",
  },
};
