/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveysSubmitRouteImport } from './routes/surveys.submit'
import { Route as ClassRoomCdRouteImport } from './routes/class-room.cd'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as AppMyLearningPathsRouteImport } from './routes/_app/my-learning-paths'
import { Route as AppMyGamificationRouteImport } from './routes/_app/my-gamification'
import { Route as AppMyClassRouteImport } from './routes/_app/my-class'
import { Route as AppMyAssignmentsRouteImport } from './routes/_app/my-assignments'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppMyClassIdRouteImport } from './routes/_app/my-class.$id'
import { Route as AppAdminSurveysRouteImport } from './routes/_app/admin.surveys'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin.roles'
import { Route as AppAdminPlansRouteImport } from './routes/_app/admin.plans'
import { Route as AppAdminOnlineCourseRouteImport } from './routes/_app/admin.online-course'
import { Route as AppAdminLearningPathsRouteImport } from './routes/_app/admin.learning-paths'
import { Route as AppAdminGamificationsRouteImport } from './routes/_app/admin.gamifications'
import { Route as AppAdminFlashcardsRouteImport } from './routes/_app/admin.flashcards'
import { Route as AppAdminEmployeesRouteImport } from './routes/_app/admin.employees'
import { Route as AppAdminDepartmentsRouteImport } from './routes/_app/admin.departments'
import { Route as AppAdminClassRoomRouteImport } from './routes/_app/admin.class-room'
import { Route as AppAdminCertificatesRouteImport } from './routes/_app/admin.certificates'
import { Route as AppAdminBranchesRouteImport } from './routes/_app/admin.branches'
import { Route as AppAdminAssignmentsRouteImport } from './routes/_app/admin.assignments'
import { Route as AppAdminAnalyticRouteImport } from './routes/_app/admin.analytic'
import { Route as AppMyAssignmentsIdSubmitRouteImport } from './routes/_app/my-assignments.$id.submit'
import { Route as AppAdminSurveysCreateRouteImport } from './routes/_app/admin.surveys.create'
import { Route as AppAdminPlansCreateRouteImport } from './routes/_app/admin.plans.create'
import { Route as AppAdminOnlineCourseIdRouteImport } from './routes/_app/admin.online-course.$id'
import { Route as AppAdminLearningPathsCreateRouteImport } from './routes/_app/admin.learning-paths.create'
import { Route as AppAdminLearningPathsIdRouteImport } from './routes/_app/admin.learning-paths.$id'
import { Route as AppAdminFlashcardsCreateRouteImport } from './routes/_app/admin.flashcards.create'
import { Route as AppAdminEmployeesIdRouteImport } from './routes/_app/admin.employees.$id'
import { Route as AppAdminClassRoomCreateRouteImport } from './routes/_app/admin.class-room.create'
import { Route as AppAdminClassRoomIdRouteImport } from './routes/_app/admin.class-room.$id'
import { Route as AppAdminCertificatesCreateRouteImport } from './routes/_app/admin.certificates.create'
import { Route as AppAdminAssignmentsQuestionBankRouteImport } from './routes/_app/admin.assignments.question-bank'
import { Route as AppAdminAssignmentsAssignedRouteImport } from './routes/_app/admin.assignments.assigned'
import { Route as AppAdminAssignmentsIdRouteImport } from './routes/_app/admin.assignments.$id'
import { Route as AppAdminClassRoomIdStudentsRouteImport } from './routes/_app/admin.class-room.$id.students'
import { Route as AppAdminAssignmentsIdGradeRouteImport } from './routes/_app/admin.assignments.$id.grade'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysSubmitRoute = SurveysSubmitRouteImport.update({
  id: '/surveys/submit',
  path: '/surveys/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassRoomCdRoute = ClassRoomCdRouteImport.update({
  id: '/class-room/cd',
  path: '/class-room/cd',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMyLearningPathsRoute = AppMyLearningPathsRouteImport.update({
  id: '/my-learning-paths',
  path: '/my-learning-paths',
  getParentRoute: () => AppRoute,
} as any)
const AppMyGamificationRoute = AppMyGamificationRouteImport.update({
  id: '/my-gamification',
  path: '/my-gamification',
  getParentRoute: () => AppRoute,
} as any)
const AppMyClassRoute = AppMyClassRouteImport.update({
  id: '/my-class',
  path: '/my-class',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAssignmentsRoute = AppMyAssignmentsRouteImport.update({
  id: '/my-assignments',
  path: '/my-assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMyClassIdRoute = AppMyClassIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMyClassRoute,
} as any)
const AppAdminSurveysRoute = AppAdminSurveysRouteImport.update({
  id: '/admin/surveys',
  path: '/admin/surveys',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPlansRoute = AppAdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOnlineCourseRoute = AppAdminOnlineCourseRouteImport.update({
  id: '/admin/online-course',
  path: '/admin/online-course',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLearningPathsRoute = AppAdminLearningPathsRouteImport.update({
  id: '/admin/learning-paths',
  path: '/admin/learning-paths',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminGamificationsRoute = AppAdminGamificationsRouteImport.update({
  id: '/admin/gamifications',
  path: '/admin/gamifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFlashcardsRoute = AppAdminFlashcardsRouteImport.update({
  id: '/admin/flashcards',
  path: '/admin/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmployeesRoute = AppAdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDepartmentsRoute = AppAdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminClassRoomRoute = AppAdminClassRoomRouteImport.update({
  id: '/admin/class-room',
  path: '/admin/class-room',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCertificatesRoute = AppAdminCertificatesRouteImport.update({
  id: '/admin/certificates',
  path: '/admin/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBranchesRoute = AppAdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/admin/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAssignmentsRoute = AppAdminAssignmentsRouteImport.update({
  id: '/admin/assignments',
  path: '/admin/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAnalyticRoute = AppAdminAnalyticRouteImport.update({
  id: '/admin/analytic',
  path: '/admin/analytic',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAssignmentsIdSubmitRoute =
  AppMyAssignmentsIdSubmitRouteImport.update({
    id: '/$id/submit',
    path: '/$id/submit',
    getParentRoute: () => AppMyAssignmentsRoute,
  } as any)
const AppAdminSurveysCreateRoute = AppAdminSurveysCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppAdminSurveysRoute,
} as any)
const AppAdminPlansCreateRoute = AppAdminPlansCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppAdminPlansRoute,
} as any)
const AppAdminOnlineCourseIdRoute = AppAdminOnlineCourseIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminOnlineCourseRoute,
} as any)
const AppAdminLearningPathsCreateRoute =
  AppAdminLearningPathsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppAdminLearningPathsRoute,
  } as any)
const AppAdminLearningPathsIdRoute = AppAdminLearningPathsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminLearningPathsRoute,
} as any)
const AppAdminFlashcardsCreateRoute =
  AppAdminFlashcardsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppAdminFlashcardsRoute,
  } as any)
const AppAdminEmployeesIdRoute = AppAdminEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminEmployeesRoute,
} as any)
const AppAdminClassRoomCreateRoute = AppAdminClassRoomCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppAdminClassRoomRoute,
} as any)
const AppAdminClassRoomIdRoute = AppAdminClassRoomIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminClassRoomRoute,
} as any)
const AppAdminCertificatesCreateRoute =
  AppAdminCertificatesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppAdminCertificatesRoute,
  } as any)
const AppAdminAssignmentsQuestionBankRoute =
  AppAdminAssignmentsQuestionBankRouteImport.update({
    id: '/question-bank',
    path: '/question-bank',
    getParentRoute: () => AppAdminAssignmentsRoute,
  } as any)
const AppAdminAssignmentsAssignedRoute =
  AppAdminAssignmentsAssignedRouteImport.update({
    id: '/assigned',
    path: '/assigned',
    getParentRoute: () => AppAdminAssignmentsRoute,
  } as any)
const AppAdminAssignmentsIdRoute = AppAdminAssignmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminAssignmentsRoute,
} as any)
const AppAdminClassRoomIdStudentsRoute =
  AppAdminClassRoomIdStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AppAdminClassRoomIdRoute,
  } as any)
const AppAdminAssignmentsIdGradeRoute =
  AppAdminAssignmentsIdGradeRouteImport.update({
    id: '/grade',
    path: '/grade',
    getParentRoute: () => AppAdminAssignmentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/library': typeof AppLibraryRoute
  '/my-assignments': typeof AppMyAssignmentsRouteWithChildren
  '/my-class': typeof AppMyClassRouteWithChildren
  '/my-gamification': typeof AppMyGamificationRoute
  '/my-learning-paths': typeof AppMyLearningPathsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/class-room/cd': typeof ClassRoomCdRoute
  '/surveys/submit': typeof SurveysSubmitRoute
  '/admin/analytic': typeof AppAdminAnalyticRoute
  '/admin/assignments': typeof AppAdminAssignmentsRouteWithChildren
  '/admin/branches': typeof AppAdminBranchesRoute
  '/admin/certificates': typeof AppAdminCertificatesRouteWithChildren
  '/admin/class-room': typeof AppAdminClassRoomRouteWithChildren
  '/admin/departments': typeof AppAdminDepartmentsRoute
  '/admin/employees': typeof AppAdminEmployeesRouteWithChildren
  '/admin/flashcards': typeof AppAdminFlashcardsRouteWithChildren
  '/admin/gamifications': typeof AppAdminGamificationsRoute
  '/admin/learning-paths': typeof AppAdminLearningPathsRouteWithChildren
  '/admin/online-course': typeof AppAdminOnlineCourseRouteWithChildren
  '/admin/plans': typeof AppAdminPlansRouteWithChildren
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/surveys': typeof AppAdminSurveysRouteWithChildren
  '/my-class/$id': typeof AppMyClassIdRoute
  '/admin/assignments/$id': typeof AppAdminAssignmentsIdRouteWithChildren
  '/admin/assignments/assigned': typeof AppAdminAssignmentsAssignedRoute
  '/admin/assignments/question-bank': typeof AppAdminAssignmentsQuestionBankRoute
  '/admin/certificates/create': typeof AppAdminCertificatesCreateRoute
  '/admin/class-room/$id': typeof AppAdminClassRoomIdRouteWithChildren
  '/admin/class-room/create': typeof AppAdminClassRoomCreateRoute
  '/admin/employees/$id': typeof AppAdminEmployeesIdRoute
  '/admin/flashcards/create': typeof AppAdminFlashcardsCreateRoute
  '/admin/learning-paths/$id': typeof AppAdminLearningPathsIdRoute
  '/admin/learning-paths/create': typeof AppAdminLearningPathsCreateRoute
  '/admin/online-course/$id': typeof AppAdminOnlineCourseIdRoute
  '/admin/plans/create': typeof AppAdminPlansCreateRoute
  '/admin/surveys/create': typeof AppAdminSurveysCreateRoute
  '/my-assignments/$id/submit': typeof AppMyAssignmentsIdSubmitRoute
  '/admin/assignments/$id/grade': typeof AppAdminAssignmentsIdGradeRoute
  '/admin/class-room/$id/students': typeof AppAdminClassRoomIdStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/library': typeof AppLibraryRoute
  '/my-assignments': typeof AppMyAssignmentsRouteWithChildren
  '/my-class': typeof AppMyClassRouteWithChildren
  '/my-gamification': typeof AppMyGamificationRoute
  '/my-learning-paths': typeof AppMyLearningPathsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/class-room/cd': typeof ClassRoomCdRoute
  '/surveys/submit': typeof SurveysSubmitRoute
  '/admin/analytic': typeof AppAdminAnalyticRoute
  '/admin/assignments': typeof AppAdminAssignmentsRouteWithChildren
  '/admin/branches': typeof AppAdminBranchesRoute
  '/admin/certificates': typeof AppAdminCertificatesRouteWithChildren
  '/admin/class-room': typeof AppAdminClassRoomRouteWithChildren
  '/admin/departments': typeof AppAdminDepartmentsRoute
  '/admin/employees': typeof AppAdminEmployeesRouteWithChildren
  '/admin/flashcards': typeof AppAdminFlashcardsRouteWithChildren
  '/admin/gamifications': typeof AppAdminGamificationsRoute
  '/admin/learning-paths': typeof AppAdminLearningPathsRouteWithChildren
  '/admin/online-course': typeof AppAdminOnlineCourseRouteWithChildren
  '/admin/plans': typeof AppAdminPlansRouteWithChildren
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/surveys': typeof AppAdminSurveysRouteWithChildren
  '/my-class/$id': typeof AppMyClassIdRoute
  '/admin/assignments/$id': typeof AppAdminAssignmentsIdRouteWithChildren
  '/admin/assignments/assigned': typeof AppAdminAssignmentsAssignedRoute
  '/admin/assignments/question-bank': typeof AppAdminAssignmentsQuestionBankRoute
  '/admin/certificates/create': typeof AppAdminCertificatesCreateRoute
  '/admin/class-room/$id': typeof AppAdminClassRoomIdRouteWithChildren
  '/admin/class-room/create': typeof AppAdminClassRoomCreateRoute
  '/admin/employees/$id': typeof AppAdminEmployeesIdRoute
  '/admin/flashcards/create': typeof AppAdminFlashcardsCreateRoute
  '/admin/learning-paths/$id': typeof AppAdminLearningPathsIdRoute
  '/admin/learning-paths/create': typeof AppAdminLearningPathsCreateRoute
  '/admin/online-course/$id': typeof AppAdminOnlineCourseIdRoute
  '/admin/plans/create': typeof AppAdminPlansCreateRoute
  '/admin/surveys/create': typeof AppAdminSurveysCreateRoute
  '/my-assignments/$id/submit': typeof AppMyAssignmentsIdSubmitRoute
  '/admin/assignments/$id/grade': typeof AppAdminAssignmentsIdGradeRoute
  '/admin/class-room/$id/students': typeof AppAdminClassRoomIdStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/my-assignments': typeof AppMyAssignmentsRouteWithChildren
  '/_app/my-class': typeof AppMyClassRouteWithChildren
  '/_app/my-gamification': typeof AppMyGamificationRoute
  '/_app/my-learning-paths': typeof AppMyLearningPathsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/class-room/cd': typeof ClassRoomCdRoute
  '/surveys/submit': typeof SurveysSubmitRoute
  '/_app/admin/analytic': typeof AppAdminAnalyticRoute
  '/_app/admin/assignments': typeof AppAdminAssignmentsRouteWithChildren
  '/_app/admin/branches': typeof AppAdminBranchesRoute
  '/_app/admin/certificates': typeof AppAdminCertificatesRouteWithChildren
  '/_app/admin/class-room': typeof AppAdminClassRoomRouteWithChildren
  '/_app/admin/departments': typeof AppAdminDepartmentsRoute
  '/_app/admin/employees': typeof AppAdminEmployeesRouteWithChildren
  '/_app/admin/flashcards': typeof AppAdminFlashcardsRouteWithChildren
  '/_app/admin/gamifications': typeof AppAdminGamificationsRoute
  '/_app/admin/learning-paths': typeof AppAdminLearningPathsRouteWithChildren
  '/_app/admin/online-course': typeof AppAdminOnlineCourseRouteWithChildren
  '/_app/admin/plans': typeof AppAdminPlansRouteWithChildren
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/surveys': typeof AppAdminSurveysRouteWithChildren
  '/_app/my-class/$id': typeof AppMyClassIdRoute
  '/_app/admin/assignments/$id': typeof AppAdminAssignmentsIdRouteWithChildren
  '/_app/admin/assignments/assigned': typeof AppAdminAssignmentsAssignedRoute
  '/_app/admin/assignments/question-bank': typeof AppAdminAssignmentsQuestionBankRoute
  '/_app/admin/certificates/create': typeof AppAdminCertificatesCreateRoute
  '/_app/admin/class-room/$id': typeof AppAdminClassRoomIdRouteWithChildren
  '/_app/admin/class-room/create': typeof AppAdminClassRoomCreateRoute
  '/_app/admin/employees/$id': typeof AppAdminEmployeesIdRoute
  '/_app/admin/flashcards/create': typeof AppAdminFlashcardsCreateRoute
  '/_app/admin/learning-paths/$id': typeof AppAdminLearningPathsIdRoute
  '/_app/admin/learning-paths/create': typeof AppAdminLearningPathsCreateRoute
  '/_app/admin/online-course/$id': typeof AppAdminOnlineCourseIdRoute
  '/_app/admin/plans/create': typeof AppAdminPlansCreateRoute
  '/_app/admin/surveys/create': typeof AppAdminSurveysCreateRoute
  '/_app/my-assignments/$id/submit': typeof AppMyAssignmentsIdSubmitRoute
  '/_app/admin/assignments/$id/grade': typeof AppAdminAssignmentsIdGradeRoute
  '/_app/admin/class-room/$id/students': typeof AppAdminClassRoomIdStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/library'
    | '/my-assignments'
    | '/my-class'
    | '/my-gamification'
    | '/my-learning-paths'
    | '/auth/signin'
    | '/auth/signup'
    | '/class-room/cd'
    | '/surveys/submit'
    | '/admin/analytic'
    | '/admin/assignments'
    | '/admin/branches'
    | '/admin/certificates'
    | '/admin/class-room'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/flashcards'
    | '/admin/gamifications'
    | '/admin/learning-paths'
    | '/admin/online-course'
    | '/admin/plans'
    | '/admin/roles'
    | '/admin/surveys'
    | '/my-class/$id'
    | '/admin/assignments/$id'
    | '/admin/assignments/assigned'
    | '/admin/assignments/question-bank'
    | '/admin/certificates/create'
    | '/admin/class-room/$id'
    | '/admin/class-room/create'
    | '/admin/employees/$id'
    | '/admin/flashcards/create'
    | '/admin/learning-paths/$id'
    | '/admin/learning-paths/create'
    | '/admin/online-course/$id'
    | '/admin/plans/create'
    | '/admin/surveys/create'
    | '/my-assignments/$id/submit'
    | '/admin/assignments/$id/grade'
    | '/admin/class-room/$id/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/library'
    | '/my-assignments'
    | '/my-class'
    | '/my-gamification'
    | '/my-learning-paths'
    | '/auth/signin'
    | '/auth/signup'
    | '/class-room/cd'
    | '/surveys/submit'
    | '/admin/analytic'
    | '/admin/assignments'
    | '/admin/branches'
    | '/admin/certificates'
    | '/admin/class-room'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/flashcards'
    | '/admin/gamifications'
    | '/admin/learning-paths'
    | '/admin/online-course'
    | '/admin/plans'
    | '/admin/roles'
    | '/admin/surveys'
    | '/my-class/$id'
    | '/admin/assignments/$id'
    | '/admin/assignments/assigned'
    | '/admin/assignments/question-bank'
    | '/admin/certificates/create'
    | '/admin/class-room/$id'
    | '/admin/class-room/create'
    | '/admin/employees/$id'
    | '/admin/flashcards/create'
    | '/admin/learning-paths/$id'
    | '/admin/learning-paths/create'
    | '/admin/online-course/$id'
    | '/admin/plans/create'
    | '/admin/surveys/create'
    | '/my-assignments/$id/submit'
    | '/admin/assignments/$id/grade'
    | '/admin/class-room/$id/students'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/library'
    | '/_app/my-assignments'
    | '/_app/my-class'
    | '/_app/my-gamification'
    | '/_app/my-learning-paths'
    | '/auth/signin'
    | '/auth/signup'
    | '/class-room/cd'
    | '/surveys/submit'
    | '/_app/admin/analytic'
    | '/_app/admin/assignments'
    | '/_app/admin/branches'
    | '/_app/admin/certificates'
    | '/_app/admin/class-room'
    | '/_app/admin/departments'
    | '/_app/admin/employees'
    | '/_app/admin/flashcards'
    | '/_app/admin/gamifications'
    | '/_app/admin/learning-paths'
    | '/_app/admin/online-course'
    | '/_app/admin/plans'
    | '/_app/admin/roles'
    | '/_app/admin/surveys'
    | '/_app/my-class/$id'
    | '/_app/admin/assignments/$id'
    | '/_app/admin/assignments/assigned'
    | '/_app/admin/assignments/question-bank'
    | '/_app/admin/certificates/create'
    | '/_app/admin/class-room/$id'
    | '/_app/admin/class-room/create'
    | '/_app/admin/employees/$id'
    | '/_app/admin/flashcards/create'
    | '/_app/admin/learning-paths/$id'
    | '/_app/admin/learning-paths/create'
    | '/_app/admin/online-course/$id'
    | '/_app/admin/plans/create'
    | '/_app/admin/surveys/create'
    | '/_app/my-assignments/$id/submit'
    | '/_app/admin/assignments/$id/grade'
    | '/_app/admin/class-room/$id/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ClassRoomCdRoute: typeof ClassRoomCdRoute
  SurveysSubmitRoute: typeof SurveysSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/submit': {
      id: '/surveys/submit'
      path: '/surveys/submit'
      fullPath: '/surveys/submit'
      preLoaderRoute: typeof SurveysSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-room/cd': {
      id: '/class-room/cd'
      path: '/class-room/cd'
      fullPath: '/class-room/cd'
      preLoaderRoute: typeof ClassRoomCdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/my-learning-paths': {
      id: '/_app/my-learning-paths'
      path: '/my-learning-paths'
      fullPath: '/my-learning-paths'
      preLoaderRoute: typeof AppMyLearningPathsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-gamification': {
      id: '/_app/my-gamification'
      path: '/my-gamification'
      fullPath: '/my-gamification'
      preLoaderRoute: typeof AppMyGamificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-class': {
      id: '/_app/my-class'
      path: '/my-class'
      fullPath: '/my-class'
      preLoaderRoute: typeof AppMyClassRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-assignments': {
      id: '/_app/my-assignments'
      path: '/my-assignments'
      fullPath: '/my-assignments'
      preLoaderRoute: typeof AppMyAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-class/$id': {
      id: '/_app/my-class/$id'
      path: '/$id'
      fullPath: '/my-class/$id'
      preLoaderRoute: typeof AppMyClassIdRouteImport
      parentRoute: typeof AppMyClassRoute
    }
    '/_app/admin/surveys': {
      id: '/_app/admin/surveys'
      path: '/admin/surveys'
      fullPath: '/admin/surveys'
      preLoaderRoute: typeof AppAdminSurveysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/plans': {
      id: '/_app/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AppAdminPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/online-course': {
      id: '/_app/admin/online-course'
      path: '/admin/online-course'
      fullPath: '/admin/online-course'
      preLoaderRoute: typeof AppAdminOnlineCourseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/learning-paths': {
      id: '/_app/admin/learning-paths'
      path: '/admin/learning-paths'
      fullPath: '/admin/learning-paths'
      preLoaderRoute: typeof AppAdminLearningPathsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/gamifications': {
      id: '/_app/admin/gamifications'
      path: '/admin/gamifications'
      fullPath: '/admin/gamifications'
      preLoaderRoute: typeof AppAdminGamificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/flashcards': {
      id: '/_app/admin/flashcards'
      path: '/admin/flashcards'
      fullPath: '/admin/flashcards'
      preLoaderRoute: typeof AppAdminFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/employees': {
      id: '/_app/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AppAdminEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/departments': {
      id: '/_app/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AppAdminDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/class-room': {
      id: '/_app/admin/class-room'
      path: '/admin/class-room'
      fullPath: '/admin/class-room'
      preLoaderRoute: typeof AppAdminClassRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/certificates': {
      id: '/_app/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AppAdminCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/branches': {
      id: '/_app/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AppAdminBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/assignments': {
      id: '/_app/admin/assignments'
      path: '/admin/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AppAdminAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/analytic': {
      id: '/_app/admin/analytic'
      path: '/admin/analytic'
      fullPath: '/admin/analytic'
      preLoaderRoute: typeof AppAdminAnalyticRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-assignments/$id/submit': {
      id: '/_app/my-assignments/$id/submit'
      path: '/$id/submit'
      fullPath: '/my-assignments/$id/submit'
      preLoaderRoute: typeof AppMyAssignmentsIdSubmitRouteImport
      parentRoute: typeof AppMyAssignmentsRoute
    }
    '/_app/admin/surveys/create': {
      id: '/_app/admin/surveys/create'
      path: '/create'
      fullPath: '/admin/surveys/create'
      preLoaderRoute: typeof AppAdminSurveysCreateRouteImport
      parentRoute: typeof AppAdminSurveysRoute
    }
    '/_app/admin/plans/create': {
      id: '/_app/admin/plans/create'
      path: '/create'
      fullPath: '/admin/plans/create'
      preLoaderRoute: typeof AppAdminPlansCreateRouteImport
      parentRoute: typeof AppAdminPlansRoute
    }
    '/_app/admin/online-course/$id': {
      id: '/_app/admin/online-course/$id'
      path: '/$id'
      fullPath: '/admin/online-course/$id'
      preLoaderRoute: typeof AppAdminOnlineCourseIdRouteImport
      parentRoute: typeof AppAdminOnlineCourseRoute
    }
    '/_app/admin/learning-paths/create': {
      id: '/_app/admin/learning-paths/create'
      path: '/create'
      fullPath: '/admin/learning-paths/create'
      preLoaderRoute: typeof AppAdminLearningPathsCreateRouteImport
      parentRoute: typeof AppAdminLearningPathsRoute
    }
    '/_app/admin/learning-paths/$id': {
      id: '/_app/admin/learning-paths/$id'
      path: '/$id'
      fullPath: '/admin/learning-paths/$id'
      preLoaderRoute: typeof AppAdminLearningPathsIdRouteImport
      parentRoute: typeof AppAdminLearningPathsRoute
    }
    '/_app/admin/flashcards/create': {
      id: '/_app/admin/flashcards/create'
      path: '/create'
      fullPath: '/admin/flashcards/create'
      preLoaderRoute: typeof AppAdminFlashcardsCreateRouteImport
      parentRoute: typeof AppAdminFlashcardsRoute
    }
    '/_app/admin/employees/$id': {
      id: '/_app/admin/employees/$id'
      path: '/$id'
      fullPath: '/admin/employees/$id'
      preLoaderRoute: typeof AppAdminEmployeesIdRouteImport
      parentRoute: typeof AppAdminEmployeesRoute
    }
    '/_app/admin/class-room/create': {
      id: '/_app/admin/class-room/create'
      path: '/create'
      fullPath: '/admin/class-room/create'
      preLoaderRoute: typeof AppAdminClassRoomCreateRouteImport
      parentRoute: typeof AppAdminClassRoomRoute
    }
    '/_app/admin/class-room/$id': {
      id: '/_app/admin/class-room/$id'
      path: '/$id'
      fullPath: '/admin/class-room/$id'
      preLoaderRoute: typeof AppAdminClassRoomIdRouteImport
      parentRoute: typeof AppAdminClassRoomRoute
    }
    '/_app/admin/certificates/create': {
      id: '/_app/admin/certificates/create'
      path: '/create'
      fullPath: '/admin/certificates/create'
      preLoaderRoute: typeof AppAdminCertificatesCreateRouteImport
      parentRoute: typeof AppAdminCertificatesRoute
    }
    '/_app/admin/assignments/question-bank': {
      id: '/_app/admin/assignments/question-bank'
      path: '/question-bank'
      fullPath: '/admin/assignments/question-bank'
      preLoaderRoute: typeof AppAdminAssignmentsQuestionBankRouteImport
      parentRoute: typeof AppAdminAssignmentsRoute
    }
    '/_app/admin/assignments/assigned': {
      id: '/_app/admin/assignments/assigned'
      path: '/assigned'
      fullPath: '/admin/assignments/assigned'
      preLoaderRoute: typeof AppAdminAssignmentsAssignedRouteImport
      parentRoute: typeof AppAdminAssignmentsRoute
    }
    '/_app/admin/assignments/$id': {
      id: '/_app/admin/assignments/$id'
      path: '/$id'
      fullPath: '/admin/assignments/$id'
      preLoaderRoute: typeof AppAdminAssignmentsIdRouteImport
      parentRoute: typeof AppAdminAssignmentsRoute
    }
    '/_app/admin/class-room/$id/students': {
      id: '/_app/admin/class-room/$id/students'
      path: '/students'
      fullPath: '/admin/class-room/$id/students'
      preLoaderRoute: typeof AppAdminClassRoomIdStudentsRouteImport
      parentRoute: typeof AppAdminClassRoomIdRoute
    }
    '/_app/admin/assignments/$id/grade': {
      id: '/_app/admin/assignments/$id/grade'
      path: '/grade'
      fullPath: '/admin/assignments/$id/grade'
      preLoaderRoute: typeof AppAdminAssignmentsIdGradeRouteImport
      parentRoute: typeof AppAdminAssignmentsIdRoute
    }
  }
}

interface AppMyAssignmentsRouteChildren {
  AppMyAssignmentsIdSubmitRoute: typeof AppMyAssignmentsIdSubmitRoute
}

const AppMyAssignmentsRouteChildren: AppMyAssignmentsRouteChildren = {
  AppMyAssignmentsIdSubmitRoute: AppMyAssignmentsIdSubmitRoute,
}

const AppMyAssignmentsRouteWithChildren =
  AppMyAssignmentsRoute._addFileChildren(AppMyAssignmentsRouteChildren)

interface AppMyClassRouteChildren {
  AppMyClassIdRoute: typeof AppMyClassIdRoute
}

const AppMyClassRouteChildren: AppMyClassRouteChildren = {
  AppMyClassIdRoute: AppMyClassIdRoute,
}

const AppMyClassRouteWithChildren = AppMyClassRoute._addFileChildren(
  AppMyClassRouteChildren,
)

interface AppAdminAssignmentsIdRouteChildren {
  AppAdminAssignmentsIdGradeRoute: typeof AppAdminAssignmentsIdGradeRoute
}

const AppAdminAssignmentsIdRouteChildren: AppAdminAssignmentsIdRouteChildren = {
  AppAdminAssignmentsIdGradeRoute: AppAdminAssignmentsIdGradeRoute,
}

const AppAdminAssignmentsIdRouteWithChildren =
  AppAdminAssignmentsIdRoute._addFileChildren(
    AppAdminAssignmentsIdRouteChildren,
  )

interface AppAdminAssignmentsRouteChildren {
  AppAdminAssignmentsIdRoute: typeof AppAdminAssignmentsIdRouteWithChildren
  AppAdminAssignmentsAssignedRoute: typeof AppAdminAssignmentsAssignedRoute
  AppAdminAssignmentsQuestionBankRoute: typeof AppAdminAssignmentsQuestionBankRoute
}

const AppAdminAssignmentsRouteChildren: AppAdminAssignmentsRouteChildren = {
  AppAdminAssignmentsIdRoute: AppAdminAssignmentsIdRouteWithChildren,
  AppAdminAssignmentsAssignedRoute: AppAdminAssignmentsAssignedRoute,
  AppAdminAssignmentsQuestionBankRoute: AppAdminAssignmentsQuestionBankRoute,
}

const AppAdminAssignmentsRouteWithChildren =
  AppAdminAssignmentsRoute._addFileChildren(AppAdminAssignmentsRouteChildren)

interface AppAdminCertificatesRouteChildren {
  AppAdminCertificatesCreateRoute: typeof AppAdminCertificatesCreateRoute
}

const AppAdminCertificatesRouteChildren: AppAdminCertificatesRouteChildren = {
  AppAdminCertificatesCreateRoute: AppAdminCertificatesCreateRoute,
}

const AppAdminCertificatesRouteWithChildren =
  AppAdminCertificatesRoute._addFileChildren(AppAdminCertificatesRouteChildren)

interface AppAdminClassRoomIdRouteChildren {
  AppAdminClassRoomIdStudentsRoute: typeof AppAdminClassRoomIdStudentsRoute
}

const AppAdminClassRoomIdRouteChildren: AppAdminClassRoomIdRouteChildren = {
  AppAdminClassRoomIdStudentsRoute: AppAdminClassRoomIdStudentsRoute,
}

const AppAdminClassRoomIdRouteWithChildren =
  AppAdminClassRoomIdRoute._addFileChildren(AppAdminClassRoomIdRouteChildren)

interface AppAdminClassRoomRouteChildren {
  AppAdminClassRoomIdRoute: typeof AppAdminClassRoomIdRouteWithChildren
  AppAdminClassRoomCreateRoute: typeof AppAdminClassRoomCreateRoute
}

const AppAdminClassRoomRouteChildren: AppAdminClassRoomRouteChildren = {
  AppAdminClassRoomIdRoute: AppAdminClassRoomIdRouteWithChildren,
  AppAdminClassRoomCreateRoute: AppAdminClassRoomCreateRoute,
}

const AppAdminClassRoomRouteWithChildren =
  AppAdminClassRoomRoute._addFileChildren(AppAdminClassRoomRouteChildren)

interface AppAdminEmployeesRouteChildren {
  AppAdminEmployeesIdRoute: typeof AppAdminEmployeesIdRoute
}

const AppAdminEmployeesRouteChildren: AppAdminEmployeesRouteChildren = {
  AppAdminEmployeesIdRoute: AppAdminEmployeesIdRoute,
}

const AppAdminEmployeesRouteWithChildren =
  AppAdminEmployeesRoute._addFileChildren(AppAdminEmployeesRouteChildren)

interface AppAdminFlashcardsRouteChildren {
  AppAdminFlashcardsCreateRoute: typeof AppAdminFlashcardsCreateRoute
}

const AppAdminFlashcardsRouteChildren: AppAdminFlashcardsRouteChildren = {
  AppAdminFlashcardsCreateRoute: AppAdminFlashcardsCreateRoute,
}

const AppAdminFlashcardsRouteWithChildren =
  AppAdminFlashcardsRoute._addFileChildren(AppAdminFlashcardsRouteChildren)

interface AppAdminLearningPathsRouteChildren {
  AppAdminLearningPathsIdRoute: typeof AppAdminLearningPathsIdRoute
  AppAdminLearningPathsCreateRoute: typeof AppAdminLearningPathsCreateRoute
}

const AppAdminLearningPathsRouteChildren: AppAdminLearningPathsRouteChildren = {
  AppAdminLearningPathsIdRoute: AppAdminLearningPathsIdRoute,
  AppAdminLearningPathsCreateRoute: AppAdminLearningPathsCreateRoute,
}

const AppAdminLearningPathsRouteWithChildren =
  AppAdminLearningPathsRoute._addFileChildren(
    AppAdminLearningPathsRouteChildren,
  )

interface AppAdminOnlineCourseRouteChildren {
  AppAdminOnlineCourseIdRoute: typeof AppAdminOnlineCourseIdRoute
}

const AppAdminOnlineCourseRouteChildren: AppAdminOnlineCourseRouteChildren = {
  AppAdminOnlineCourseIdRoute: AppAdminOnlineCourseIdRoute,
}

const AppAdminOnlineCourseRouteWithChildren =
  AppAdminOnlineCourseRoute._addFileChildren(AppAdminOnlineCourseRouteChildren)

interface AppAdminPlansRouteChildren {
  AppAdminPlansCreateRoute: typeof AppAdminPlansCreateRoute
}

const AppAdminPlansRouteChildren: AppAdminPlansRouteChildren = {
  AppAdminPlansCreateRoute: AppAdminPlansCreateRoute,
}

const AppAdminPlansRouteWithChildren = AppAdminPlansRoute._addFileChildren(
  AppAdminPlansRouteChildren,
)

interface AppAdminSurveysRouteChildren {
  AppAdminSurveysCreateRoute: typeof AppAdminSurveysCreateRoute
}

const AppAdminSurveysRouteChildren: AppAdminSurveysRouteChildren = {
  AppAdminSurveysCreateRoute: AppAdminSurveysCreateRoute,
}

const AppAdminSurveysRouteWithChildren = AppAdminSurveysRoute._addFileChildren(
  AppAdminSurveysRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppMyAssignmentsRoute: typeof AppMyAssignmentsRouteWithChildren
  AppMyClassRoute: typeof AppMyClassRouteWithChildren
  AppMyGamificationRoute: typeof AppMyGamificationRoute
  AppMyLearningPathsRoute: typeof AppMyLearningPathsRoute
  AppAdminAnalyticRoute: typeof AppAdminAnalyticRoute
  AppAdminAssignmentsRoute: typeof AppAdminAssignmentsRouteWithChildren
  AppAdminBranchesRoute: typeof AppAdminBranchesRoute
  AppAdminCertificatesRoute: typeof AppAdminCertificatesRouteWithChildren
  AppAdminClassRoomRoute: typeof AppAdminClassRoomRouteWithChildren
  AppAdminDepartmentsRoute: typeof AppAdminDepartmentsRoute
  AppAdminEmployeesRoute: typeof AppAdminEmployeesRouteWithChildren
  AppAdminFlashcardsRoute: typeof AppAdminFlashcardsRouteWithChildren
  AppAdminGamificationsRoute: typeof AppAdminGamificationsRoute
  AppAdminLearningPathsRoute: typeof AppAdminLearningPathsRouteWithChildren
  AppAdminOnlineCourseRoute: typeof AppAdminOnlineCourseRouteWithChildren
  AppAdminPlansRoute: typeof AppAdminPlansRouteWithChildren
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminSurveysRoute: typeof AppAdminSurveysRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppMyAssignmentsRoute: AppMyAssignmentsRouteWithChildren,
  AppMyClassRoute: AppMyClassRouteWithChildren,
  AppMyGamificationRoute: AppMyGamificationRoute,
  AppMyLearningPathsRoute: AppMyLearningPathsRoute,
  AppAdminAnalyticRoute: AppAdminAnalyticRoute,
  AppAdminAssignmentsRoute: AppAdminAssignmentsRouteWithChildren,
  AppAdminBranchesRoute: AppAdminBranchesRoute,
  AppAdminCertificatesRoute: AppAdminCertificatesRouteWithChildren,
  AppAdminClassRoomRoute: AppAdminClassRoomRouteWithChildren,
  AppAdminDepartmentsRoute: AppAdminDepartmentsRoute,
  AppAdminEmployeesRoute: AppAdminEmployeesRouteWithChildren,
  AppAdminFlashcardsRoute: AppAdminFlashcardsRouteWithChildren,
  AppAdminGamificationsRoute: AppAdminGamificationsRoute,
  AppAdminLearningPathsRoute: AppAdminLearningPathsRouteWithChildren,
  AppAdminOnlineCourseRoute: AppAdminOnlineCourseRouteWithChildren,
  AppAdminPlansRoute: AppAdminPlansRouteWithChildren,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminSurveysRoute: AppAdminSurveysRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  ClassRoomCdRoute: ClassRoomCdRoute,
  SurveysSubmitRoute: SurveysSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
