/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as NoOrganizationRouteImport } from './routes/no-organization'
import { Route as AppRouteImport } from './routes/_app'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as AuthErrorRouteImport } from './routes/auth.error'
import { Route as AppMyLearningPathsRouteImport } from './routes/_app/my-learning-paths'
import { Route as AppMyGamificationRouteImport } from './routes/_app/my-gamification'
import { Route as AppMyFlashcardsRouteImport } from './routes/_app/my-flashcards'
import { Route as AppMyFavoritesRouteImport } from './routes/_app/my-favorites'
import { Route as AppMyClassRouteImport } from './routes/_app/my-class'
import { Route as AppMyCertificatesRouteImport } from './routes/_app/my-certificates'
import { Route as AppMyAssignmentsRouteImport } from './routes/_app/my-assignments'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAnalyticRouteImport } from './routes/_app/analytic'
import { Route as AppDepartmentsIndexRouteImport } from './routes/_app/departments.index'
import { Route as AppBranchesIndexRouteImport } from './routes/_app/branches.index'
import { Route as SurveysIdSubmitRouteImport } from './routes/surveys.$id.submit'
import { Route as AppStudentDashboardRouteImport } from './routes/_app/student/dashboard'
import { Route as AppDepartmentsListRouteImport } from './routes/_app/departments.list'
import { Route as AppDepartmentsIdRouteImport } from './routes/_app/departments.$id'
import { Route as AppClassRoomSlugRouteImport } from './routes/_app/class-room.$slug'
import { Route as AppBranchesListRouteImport } from './routes/_app/branches.list'
import { Route as AppBranchesIdRouteImport } from './routes/_app/branches.$id'
import { Route as AppAdminGamificationsRouteImport } from './routes/_app/admin.gamifications'
import { Route as AppAdminDashboardRouteImport } from './routes/_app/admin/dashboard'
import { Route as AppAdminCertificatesRouteImport } from './routes/_app/admin.certificates'
import { Route as AppAdminSurveysIndexRouteImport } from './routes/_app/admin.surveys.index'
import { Route as AppAdminSurveysResultsIndexRouteImport } from './routes/_app/admin.surveys-results.index'
import { Route as AppAdminRolesIndexRouteImport } from './routes/_app/admin.roles.index'
import { Route as AppAdminPlansIndexRouteImport } from './routes/_app/admin.plans.index'
import { Route as AppAdminOnlineCourseIndexRouteImport } from './routes/_app/admin.online-course.index'
import { Route as AppAdminLearningPathsIndexRouteImport } from './routes/_app/admin.learning-paths.index'
import { Route as AppAdminFlashcardsIndexRouteImport } from './routes/_app/admin.flashcards.index'
import { Route as AppAdminEmployeesIndexRouteImport } from './routes/_app/admin.employees.index'
import { Route as AppAdminClassRoomIndexRouteImport } from './routes/_app/admin.class-room.index'
import { Route as AppAdminAssignmentsIndexRouteImport } from './routes/_app/admin.assignments.index'
import { Route as SurveysIdSubmitThankYouRouteImport } from './routes/surveys.$id.submit.thank-you'
import { Route as ClassRoomCdSlugSessionIdRouteImport } from './routes/class-room.cd.$slug.$sessionId'
import { Route as AppMyLearningPathsPhaseIdRouteImport } from './routes/_app/my-learning-paths.phase.$id'
import { Route as AppMyLearningPathsLearningScreenCourseIdRouteImport } from './routes/_app/my-learning-paths.learning-screen.$courseId'
import { Route as AppAdminSurveysListRouteImport } from './routes/_app/admin.surveys.list'
import { Route as AppAdminSurveysResultsIdRouteImport } from './routes/_app/admin.surveys-results.$id'
import { Route as AppAdminRolesCodeRouteImport } from './routes/_app/admin.roles.$code'
import { Route as AppAdminReportOverviewRouteImport } from './routes/_app/admin.report.overview'
import { Route as AppAdminPlansNewRouteImport } from './routes/_app/admin.plans.new'
import { Route as AppAdminOnlineCourseListRouteImport } from './routes/_app/admin.online-course.list'
import { Route as AppAdminLearningPathsIdRouteImport } from './routes/_app/admin.learning-paths.$id'
import { Route as AppAdminEmployeesImportRouteImport } from './routes/_app/admin.employees.import'
import { Route as AppAdminClassRoomListRouteImport } from './routes/_app/admin.class-room.list'
import { Route as AppAdminAssignmentsQuestionBankRouteImport } from './routes/_app/admin.assignments.question-bank'
import { Route as AppAdminAssignmentsAssignedRouteImport } from './routes/_app/admin.assignments.assigned'
import { Route as AppAdminPlansIdIndexRouteImport } from './routes/_app/admin.plans.$id.index'
import { Route as AppAdminOnlineCourseIdIndexRouteImport } from './routes/_app/admin.online-course.$id.index'
import { Route as AppAdminFlashcardsIdIndexRouteImport } from './routes/_app/admin.flashcards.$id.index'
import { Route as AppAdminAssignmentsIdIndexRouteImport } from './routes/_app/admin.assignments.$id.index'
import { Route as AppMyAssignmentsIdSubmitEmployeeIdRouteImport } from './routes/_app/my-assignments.$id.submit.$employeeId'
import { Route as AppMyAssignmentsIdResultEmployeeIdRouteImport } from './routes/_app/my-assignments.$id.result.$employeeId'
import { Route as AppClassRoomSlugLearningScreenCourseIdRouteImport } from './routes/_app/class-room.$slug.learning-screen.$courseId'
import { Route as AppAdminSurveysIdThankYouRouteImport } from './routes/_app/admin.surveys.$id.thank-you'
import { Route as AppAdminSurveysIdSubmissionsRouteImport } from './routes/_app/admin.surveys.$id.submissions'
import { Route as AppAdminSurveysIdStatisticsRouteImport } from './routes/_app/admin.surveys.$id.statistics'
import { Route as AppAdminSurveysIdEditRouteImport } from './routes/_app/admin.surveys.$id.edit'
import { Route as AppAdminPlansIdEditRouteImport } from './routes/_app/admin.plans.$id.edit'
import { Route as AppAdminOnlineCourseIdEditRouteImport } from './routes/_app/admin.online-course.$id.edit'
import { Route as AppAdminLearningPathsEditIdRouteImport } from './routes/_app/admin.learning-paths.edit.$id'
import { Route as AppAdminFlashcardsIdEditRouteImport } from './routes/_app/admin.flashcards.$id.edit'
import { Route as AppAdminEmployeesIdEditRouteImport } from './routes/_app/admin.employees.$id.edit'
import { Route as AppAdminEmployeesIdDetailRouteImport } from './routes/_app/admin.employees.$id.detail'
import { Route as AppAdminClassRoomIdStudentsRouteImport } from './routes/_app/admin.class-room.$id.students'
import { Route as AppAdminClassRoomIdEditRouteImport } from './routes/_app/admin.class-room.$id.edit'
import { Route as AppAdminCertificatesEditIdRouteImport } from './routes/_app/admin.certificates.edit.$id'
import { Route as AppAdminAssignmentsEditIdRouteImport } from './routes/_app/admin.assignments.edit.$id'
import { Route as AppAdminAssignmentsIdStudentsRouteImport } from './routes/_app/admin.assignments.$id.students'
import { Route as AppAdminAssignmentsIdAssignRouteImport } from './routes/_app/admin.assignments.$id.assign'
import { Route as AppAdminAssignmentsQuestionBankIdEditRouteImport } from './routes/_app/admin.assignments.question-bank.$id.edit'
import { Route as AppAdminAssignmentsIdSubmitEmployeeIdRouteImport } from './routes/_app/admin.assignments.$id.submit.$employeeId'
import { Route as AppAdminAssignmentsIdResultEmployeeIdRouteImport } from './routes/_app/admin.assignments.$id.result.$employeeId'
import { Route as AppAdminAssignmentsIdGradeEmployeeIdRouteImport } from './routes/_app/admin.assignments.$id.grade.$employeeId'

const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const NoOrganizationRoute = NoOrganizationRouteImport.update({
  id: '/no-organization',
  path: '/no-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMyLearningPathsRoute = AppMyLearningPathsRouteImport.update({
  id: '/my-learning-paths',
  path: '/my-learning-paths',
  getParentRoute: () => AppRoute,
} as any)
const AppMyGamificationRoute = AppMyGamificationRouteImport.update({
  id: '/my-gamification',
  path: '/my-gamification',
  getParentRoute: () => AppRoute,
} as any)
const AppMyFlashcardsRoute = AppMyFlashcardsRouteImport.update({
  id: '/my-flashcards',
  path: '/my-flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppMyFavoritesRoute = AppMyFavoritesRouteImport.update({
  id: '/my-favorites',
  path: '/my-favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppMyClassRoute = AppMyClassRouteImport.update({
  id: '/my-class',
  path: '/my-class',
  getParentRoute: () => AppRoute,
} as any)
const AppMyCertificatesRoute = AppMyCertificatesRouteImport.update({
  id: '/my-certificates',
  path: '/my-certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAssignmentsRoute = AppMyAssignmentsRouteImport.update({
  id: '/my-assignments',
  path: '/my-assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticRoute = AppAnalyticRouteImport.update({
  id: '/analytic',
  path: '/analytic',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsIndexRoute = AppDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesIndexRoute = AppBranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => AppRoute,
} as any)
const SurveysIdSubmitRoute = SurveysIdSubmitRouteImport.update({
  id: '/surveys/$id/submit',
  path: '/surveys/$id/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudentDashboardRoute = AppStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsListRoute = AppDepartmentsListRouteImport.update({
  id: '/departments/list',
  path: '/departments/list',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsIdRoute = AppDepartmentsIdRouteImport.update({
  id: '/departments/$id',
  path: '/departments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClassRoomSlugRoute = AppClassRoomSlugRouteImport.update({
  id: '/class-room/$slug',
  path: '/class-room/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesListRoute = AppBranchesListRouteImport.update({
  id: '/branches/list',
  path: '/branches/list',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesIdRoute = AppBranchesIdRouteImport.update({
  id: '/branches/$id',
  path: '/branches/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminGamificationsRoute = AppAdminGamificationsRouteImport.update({
  id: '/admin/gamifications',
  path: '/admin/gamifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCertificatesRoute = AppAdminCertificatesRouteImport.update({
  id: '/admin/certificates',
  path: '/admin/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSurveysIndexRoute = AppAdminSurveysIndexRouteImport.update({
  id: '/admin/surveys/',
  path: '/admin/surveys/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSurveysResultsIndexRoute =
  AppAdminSurveysResultsIndexRouteImport.update({
    id: '/admin/surveys-results/',
    path: '/admin/surveys-results/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminRolesIndexRoute = AppAdminRolesIndexRouteImport.update({
  id: '/admin/roles/',
  path: '/admin/roles/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPlansIndexRoute = AppAdminPlansIndexRouteImport.update({
  id: '/admin/plans/',
  path: '/admin/plans/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOnlineCourseIndexRoute =
  AppAdminOnlineCourseIndexRouteImport.update({
    id: '/admin/online-course/',
    path: '/admin/online-course/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminLearningPathsIndexRoute =
  AppAdminLearningPathsIndexRouteImport.update({
    id: '/admin/learning-paths/',
    path: '/admin/learning-paths/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminFlashcardsIndexRoute = AppAdminFlashcardsIndexRouteImport.update({
  id: '/admin/flashcards/',
  path: '/admin/flashcards/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmployeesIndexRoute = AppAdminEmployeesIndexRouteImport.update({
  id: '/admin/employees/',
  path: '/admin/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminClassRoomIndexRoute = AppAdminClassRoomIndexRouteImport.update({
  id: '/admin/class-room/',
  path: '/admin/class-room/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAssignmentsIndexRoute =
  AppAdminAssignmentsIndexRouteImport.update({
    id: '/admin/assignments/',
    path: '/admin/assignments/',
    getParentRoute: () => AppRoute,
  } as any)
const SurveysIdSubmitThankYouRoute = SurveysIdSubmitThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => SurveysIdSubmitRoute,
} as any)
const ClassRoomCdSlugSessionIdRoute =
  ClassRoomCdSlugSessionIdRouteImport.update({
    id: '/class-room/cd/$slug/$sessionId',
    path: '/class-room/cd/$slug/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppMyLearningPathsPhaseIdRoute =
  AppMyLearningPathsPhaseIdRouteImport.update({
    id: '/phase/$id',
    path: '/phase/$id',
    getParentRoute: () => AppMyLearningPathsRoute,
  } as any)
const AppMyLearningPathsLearningScreenCourseIdRoute =
  AppMyLearningPathsLearningScreenCourseIdRouteImport.update({
    id: '/learning-screen/$courseId',
    path: '/learning-screen/$courseId',
    getParentRoute: () => AppMyLearningPathsRoute,
  } as any)
const AppAdminSurveysListRoute = AppAdminSurveysListRouteImport.update({
  id: '/admin/surveys/list',
  path: '/admin/surveys/list',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSurveysResultsIdRoute =
  AppAdminSurveysResultsIdRouteImport.update({
    id: '/admin/surveys-results/$id',
    path: '/admin/surveys-results/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminRolesCodeRoute = AppAdminRolesCodeRouteImport.update({
  id: '/admin/roles/$code',
  path: '/admin/roles/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportOverviewRoute = AppAdminReportOverviewRouteImport.update({
  id: '/admin/report/overview',
  path: '/admin/report/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPlansNewRoute = AppAdminPlansNewRouteImport.update({
  id: '/admin/plans/new',
  path: '/admin/plans/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOnlineCourseListRoute =
  AppAdminOnlineCourseListRouteImport.update({
    id: '/admin/online-course/list',
    path: '/admin/online-course/list',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminLearningPathsIdRoute = AppAdminLearningPathsIdRouteImport.update({
  id: '/admin/learning-paths/$id',
  path: '/admin/learning-paths/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmployeesImportRoute = AppAdminEmployeesImportRouteImport.update({
  id: '/admin/employees/import',
  path: '/admin/employees/import',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminClassRoomListRoute = AppAdminClassRoomListRouteImport.update({
  id: '/admin/class-room/list',
  path: '/admin/class-room/list',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAssignmentsQuestionBankRoute =
  AppAdminAssignmentsQuestionBankRouteImport.update({
    id: '/admin/assignments/question-bank',
    path: '/admin/assignments/question-bank',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAssignmentsAssignedRoute =
  AppAdminAssignmentsAssignedRouteImport.update({
    id: '/admin/assignments/assigned',
    path: '/admin/assignments/assigned',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminPlansIdIndexRoute = AppAdminPlansIdIndexRouteImport.update({
  id: '/admin/plans/$id/',
  path: '/admin/plans/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOnlineCourseIdIndexRoute =
  AppAdminOnlineCourseIdIndexRouteImport.update({
    id: '/admin/online-course/$id/',
    path: '/admin/online-course/$id/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminFlashcardsIdIndexRoute =
  AppAdminFlashcardsIdIndexRouteImport.update({
    id: '/admin/flashcards/$id/',
    path: '/admin/flashcards/$id/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAssignmentsIdIndexRoute =
  AppAdminAssignmentsIdIndexRouteImport.update({
    id: '/admin/assignments/$id/',
    path: '/admin/assignments/$id/',
    getParentRoute: () => AppRoute,
  } as any)
const AppMyAssignmentsIdSubmitEmployeeIdRoute =
  AppMyAssignmentsIdSubmitEmployeeIdRouteImport.update({
    id: '/$id/submit/$employeeId',
    path: '/$id/submit/$employeeId',
    getParentRoute: () => AppMyAssignmentsRoute,
  } as any)
const AppMyAssignmentsIdResultEmployeeIdRoute =
  AppMyAssignmentsIdResultEmployeeIdRouteImport.update({
    id: '/$id/result/$employeeId',
    path: '/$id/result/$employeeId',
    getParentRoute: () => AppMyAssignmentsRoute,
  } as any)
const AppClassRoomSlugLearningScreenCourseIdRoute =
  AppClassRoomSlugLearningScreenCourseIdRouteImport.update({
    id: '/learning-screen/$courseId',
    path: '/learning-screen/$courseId',
    getParentRoute: () => AppClassRoomSlugRoute,
  } as any)
const AppAdminSurveysIdThankYouRoute =
  AppAdminSurveysIdThankYouRouteImport.update({
    id: '/admin/surveys/$id/thank-you',
    path: '/admin/surveys/$id/thank-you',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminSurveysIdSubmissionsRoute =
  AppAdminSurveysIdSubmissionsRouteImport.update({
    id: '/admin/surveys/$id/submissions',
    path: '/admin/surveys/$id/submissions',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminSurveysIdStatisticsRoute =
  AppAdminSurveysIdStatisticsRouteImport.update({
    id: '/admin/surveys/$id/statistics',
    path: '/admin/surveys/$id/statistics',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminSurveysIdEditRoute = AppAdminSurveysIdEditRouteImport.update({
  id: '/admin/surveys/$id/edit',
  path: '/admin/surveys/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPlansIdEditRoute = AppAdminPlansIdEditRouteImport.update({
  id: '/admin/plans/$id/edit',
  path: '/admin/plans/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOnlineCourseIdEditRoute =
  AppAdminOnlineCourseIdEditRouteImport.update({
    id: '/admin/online-course/$id/edit',
    path: '/admin/online-course/$id/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminLearningPathsEditIdRoute =
  AppAdminLearningPathsEditIdRouteImport.update({
    id: '/admin/learning-paths/edit/$id',
    path: '/admin/learning-paths/edit/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminFlashcardsIdEditRoute =
  AppAdminFlashcardsIdEditRouteImport.update({
    id: '/admin/flashcards/$id/edit',
    path: '/admin/flashcards/$id/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminEmployeesIdEditRoute = AppAdminEmployeesIdEditRouteImport.update({
  id: '/admin/employees/$id/edit',
  path: '/admin/employees/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmployeesIdDetailRoute =
  AppAdminEmployeesIdDetailRouteImport.update({
    id: '/admin/employees/$id/detail',
    path: '/admin/employees/$id/detail',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminClassRoomIdStudentsRoute =
  AppAdminClassRoomIdStudentsRouteImport.update({
    id: '/admin/class-room/$id/students',
    path: '/admin/class-room/$id/students',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminClassRoomIdEditRoute = AppAdminClassRoomIdEditRouteImport.update({
  id: '/admin/class-room/$id/edit',
  path: '/admin/class-room/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCertificatesEditIdRoute =
  AppAdminCertificatesEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AppAdminCertificatesRoute,
  } as any)
const AppAdminAssignmentsEditIdRoute =
  AppAdminAssignmentsEditIdRouteImport.update({
    id: '/admin/assignments/edit/$id',
    path: '/admin/assignments/edit/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAssignmentsIdStudentsRoute =
  AppAdminAssignmentsIdStudentsRouteImport.update({
    id: '/admin/assignments/$id/students',
    path: '/admin/assignments/$id/students',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAssignmentsIdAssignRoute =
  AppAdminAssignmentsIdAssignRouteImport.update({
    id: '/admin/assignments/$id/assign',
    path: '/admin/assignments/$id/assign',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAssignmentsQuestionBankIdEditRoute =
  AppAdminAssignmentsQuestionBankIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AppAdminAssignmentsQuestionBankRoute,
  } as any)
const AppAdminAssignmentsIdSubmitEmployeeIdRoute =
  AppAdminAssignmentsIdSubmitEmployeeIdRouteImport.update({
    id: '/admin/assignments/$id/submit/$employeeId',
    path: '/admin/assignments/$id/submit/$employeeId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAssignmentsIdResultEmployeeIdRoute =
  AppAdminAssignmentsIdResultEmployeeIdRouteImport.update({
    id: '/admin/assignments/$id/result/$employeeId',
    path: '/admin/assignments/$id/result/$employeeId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminAssignmentsIdGradeEmployeeIdRoute =
  AppAdminAssignmentsIdGradeEmployeeIdRouteImport.update({
    id: '/admin/assignments/$id/grade/$employeeId',
    path: '/admin/assignments/$id/grade/$employeeId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/no-organization': typeof NoOrganizationRoute
  '/organizations': typeof OrganizationsRoute
  '/analytic': typeof AppAnalyticRoute
  '/dashboard': typeof AppDashboardRoute
  '/my-assignments': typeof AppMyAssignmentsRouteWithChildren
  '/my-certificates': typeof AppMyCertificatesRoute
  '/my-class': typeof AppMyClassRoute
  '/my-favorites': typeof AppMyFavoritesRoute
  '/my-flashcards': typeof AppMyFlashcardsRoute
  '/my-gamification': typeof AppMyGamificationRoute
  '/my-learning-paths': typeof AppMyLearningPathsRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/certificates': typeof AppAdminCertificatesRouteWithChildren
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/gamifications': typeof AppAdminGamificationsRoute
  '/branches/$id': typeof AppBranchesIdRoute
  '/branches/list': typeof AppBranchesListRoute
  '/class-room/$slug': typeof AppClassRoomSlugRouteWithChildren
  '/departments/$id': typeof AppDepartmentsIdRoute
  '/departments/list': typeof AppDepartmentsListRoute
  '/student/dashboard': typeof AppStudentDashboardRoute
  '/surveys/$id/submit': typeof SurveysIdSubmitRouteWithChildren
  '/branches/': typeof AppBranchesIndexRoute
  '/departments/': typeof AppDepartmentsIndexRoute
  '/admin/assignments/assigned': typeof AppAdminAssignmentsAssignedRoute
  '/admin/assignments/question-bank': typeof AppAdminAssignmentsQuestionBankRouteWithChildren
  '/admin/class-room/list': typeof AppAdminClassRoomListRoute
  '/admin/employees/import': typeof AppAdminEmployeesImportRoute
  '/admin/learning-paths/$id': typeof AppAdminLearningPathsIdRoute
  '/admin/online-course/list': typeof AppAdminOnlineCourseListRoute
  '/admin/plans/new': typeof AppAdminPlansNewRoute
  '/admin/report/overview': typeof AppAdminReportOverviewRoute
  '/admin/roles/$code': typeof AppAdminRolesCodeRoute
  '/admin/surveys-results/$id': typeof AppAdminSurveysResultsIdRoute
  '/admin/surveys/list': typeof AppAdminSurveysListRoute
  '/my-learning-paths/learning-screen/$courseId': typeof AppMyLearningPathsLearningScreenCourseIdRoute
  '/my-learning-paths/phase/$id': typeof AppMyLearningPathsPhaseIdRoute
  '/class-room/cd/$slug/$sessionId': typeof ClassRoomCdSlugSessionIdRoute
  '/surveys/$id/submit/thank-you': typeof SurveysIdSubmitThankYouRoute
  '/admin/assignments/': typeof AppAdminAssignmentsIndexRoute
  '/admin/class-room/': typeof AppAdminClassRoomIndexRoute
  '/admin/employees/': typeof AppAdminEmployeesIndexRoute
  '/admin/flashcards/': typeof AppAdminFlashcardsIndexRoute
  '/admin/learning-paths/': typeof AppAdminLearningPathsIndexRoute
  '/admin/online-course/': typeof AppAdminOnlineCourseIndexRoute
  '/admin/plans/': typeof AppAdminPlansIndexRoute
  '/admin/roles/': typeof AppAdminRolesIndexRoute
  '/admin/surveys-results/': typeof AppAdminSurveysResultsIndexRoute
  '/admin/surveys/': typeof AppAdminSurveysIndexRoute
  '/admin/assignments/$id/assign': typeof AppAdminAssignmentsIdAssignRoute
  '/admin/assignments/$id/students': typeof AppAdminAssignmentsIdStudentsRoute
  '/admin/assignments/edit/$id': typeof AppAdminAssignmentsEditIdRoute
  '/admin/certificates/edit/$id': typeof AppAdminCertificatesEditIdRoute
  '/admin/class-room/$id/edit': typeof AppAdminClassRoomIdEditRoute
  '/admin/class-room/$id/students': typeof AppAdminClassRoomIdStudentsRoute
  '/admin/employees/$id/detail': typeof AppAdminEmployeesIdDetailRoute
  '/admin/employees/$id/edit': typeof AppAdminEmployeesIdEditRoute
  '/admin/flashcards/$id/edit': typeof AppAdminFlashcardsIdEditRoute
  '/admin/learning-paths/edit/$id': typeof AppAdminLearningPathsEditIdRoute
  '/admin/online-course/$id/edit': typeof AppAdminOnlineCourseIdEditRoute
  '/admin/plans/$id/edit': typeof AppAdminPlansIdEditRoute
  '/admin/surveys/$id/edit': typeof AppAdminSurveysIdEditRoute
  '/admin/surveys/$id/statistics': typeof AppAdminSurveysIdStatisticsRoute
  '/admin/surveys/$id/submissions': typeof AppAdminSurveysIdSubmissionsRoute
  '/admin/surveys/$id/thank-you': typeof AppAdminSurveysIdThankYouRoute
  '/class-room/$slug/learning-screen/$courseId': typeof AppClassRoomSlugLearningScreenCourseIdRoute
  '/my-assignments/$id/result/$employeeId': typeof AppMyAssignmentsIdResultEmployeeIdRoute
  '/my-assignments/$id/submit/$employeeId': typeof AppMyAssignmentsIdSubmitEmployeeIdRoute
  '/admin/assignments/$id/': typeof AppAdminAssignmentsIdIndexRoute
  '/admin/flashcards/$id/': typeof AppAdminFlashcardsIdIndexRoute
  '/admin/online-course/$id/': typeof AppAdminOnlineCourseIdIndexRoute
  '/admin/plans/$id/': typeof AppAdminPlansIdIndexRoute
  '/admin/assignments/$id/grade/$employeeId': typeof AppAdminAssignmentsIdGradeEmployeeIdRoute
  '/admin/assignments/$id/result/$employeeId': typeof AppAdminAssignmentsIdResultEmployeeIdRoute
  '/admin/assignments/$id/submit/$employeeId': typeof AppAdminAssignmentsIdSubmitEmployeeIdRoute
  '/admin/assignments/question-bank/$id/edit': typeof AppAdminAssignmentsQuestionBankIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/no-organization': typeof NoOrganizationRoute
  '/organizations': typeof OrganizationsRoute
  '/analytic': typeof AppAnalyticRoute
  '/dashboard': typeof AppDashboardRoute
  '/my-assignments': typeof AppMyAssignmentsRouteWithChildren
  '/my-certificates': typeof AppMyCertificatesRoute
  '/my-class': typeof AppMyClassRoute
  '/my-favorites': typeof AppMyFavoritesRoute
  '/my-flashcards': typeof AppMyFlashcardsRoute
  '/my-gamification': typeof AppMyGamificationRoute
  '/my-learning-paths': typeof AppMyLearningPathsRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/certificates': typeof AppAdminCertificatesRouteWithChildren
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/gamifications': typeof AppAdminGamificationsRoute
  '/branches/$id': typeof AppBranchesIdRoute
  '/branches/list': typeof AppBranchesListRoute
  '/class-room/$slug': typeof AppClassRoomSlugRouteWithChildren
  '/departments/$id': typeof AppDepartmentsIdRoute
  '/departments/list': typeof AppDepartmentsListRoute
  '/student/dashboard': typeof AppStudentDashboardRoute
  '/surveys/$id/submit': typeof SurveysIdSubmitRouteWithChildren
  '/branches': typeof AppBranchesIndexRoute
  '/departments': typeof AppDepartmentsIndexRoute
  '/admin/assignments/assigned': typeof AppAdminAssignmentsAssignedRoute
  '/admin/assignments/question-bank': typeof AppAdminAssignmentsQuestionBankRouteWithChildren
  '/admin/class-room/list': typeof AppAdminClassRoomListRoute
  '/admin/employees/import': typeof AppAdminEmployeesImportRoute
  '/admin/learning-paths/$id': typeof AppAdminLearningPathsIdRoute
  '/admin/online-course/list': typeof AppAdminOnlineCourseListRoute
  '/admin/plans/new': typeof AppAdminPlansNewRoute
  '/admin/report/overview': typeof AppAdminReportOverviewRoute
  '/admin/roles/$code': typeof AppAdminRolesCodeRoute
  '/admin/surveys-results/$id': typeof AppAdminSurveysResultsIdRoute
  '/admin/surveys/list': typeof AppAdminSurveysListRoute
  '/my-learning-paths/learning-screen/$courseId': typeof AppMyLearningPathsLearningScreenCourseIdRoute
  '/my-learning-paths/phase/$id': typeof AppMyLearningPathsPhaseIdRoute
  '/class-room/cd/$slug/$sessionId': typeof ClassRoomCdSlugSessionIdRoute
  '/surveys/$id/submit/thank-you': typeof SurveysIdSubmitThankYouRoute
  '/admin/assignments': typeof AppAdminAssignmentsIndexRoute
  '/admin/class-room': typeof AppAdminClassRoomIndexRoute
  '/admin/employees': typeof AppAdminEmployeesIndexRoute
  '/admin/flashcards': typeof AppAdminFlashcardsIndexRoute
  '/admin/learning-paths': typeof AppAdminLearningPathsIndexRoute
  '/admin/online-course': typeof AppAdminOnlineCourseIndexRoute
  '/admin/plans': typeof AppAdminPlansIndexRoute
  '/admin/roles': typeof AppAdminRolesIndexRoute
  '/admin/surveys-results': typeof AppAdminSurveysResultsIndexRoute
  '/admin/surveys': typeof AppAdminSurveysIndexRoute
  '/admin/assignments/$id/assign': typeof AppAdminAssignmentsIdAssignRoute
  '/admin/assignments/$id/students': typeof AppAdminAssignmentsIdStudentsRoute
  '/admin/assignments/edit/$id': typeof AppAdminAssignmentsEditIdRoute
  '/admin/certificates/edit/$id': typeof AppAdminCertificatesEditIdRoute
  '/admin/class-room/$id/edit': typeof AppAdminClassRoomIdEditRoute
  '/admin/class-room/$id/students': typeof AppAdminClassRoomIdStudentsRoute
  '/admin/employees/$id/detail': typeof AppAdminEmployeesIdDetailRoute
  '/admin/employees/$id/edit': typeof AppAdminEmployeesIdEditRoute
  '/admin/flashcards/$id/edit': typeof AppAdminFlashcardsIdEditRoute
  '/admin/learning-paths/edit/$id': typeof AppAdminLearningPathsEditIdRoute
  '/admin/online-course/$id/edit': typeof AppAdminOnlineCourseIdEditRoute
  '/admin/plans/$id/edit': typeof AppAdminPlansIdEditRoute
  '/admin/surveys/$id/edit': typeof AppAdminSurveysIdEditRoute
  '/admin/surveys/$id/statistics': typeof AppAdminSurveysIdStatisticsRoute
  '/admin/surveys/$id/submissions': typeof AppAdminSurveysIdSubmissionsRoute
  '/admin/surveys/$id/thank-you': typeof AppAdminSurveysIdThankYouRoute
  '/class-room/$slug/learning-screen/$courseId': typeof AppClassRoomSlugLearningScreenCourseIdRoute
  '/my-assignments/$id/result/$employeeId': typeof AppMyAssignmentsIdResultEmployeeIdRoute
  '/my-assignments/$id/submit/$employeeId': typeof AppMyAssignmentsIdSubmitEmployeeIdRoute
  '/admin/assignments/$id': typeof AppAdminAssignmentsIdIndexRoute
  '/admin/flashcards/$id': typeof AppAdminFlashcardsIdIndexRoute
  '/admin/online-course/$id': typeof AppAdminOnlineCourseIdIndexRoute
  '/admin/plans/$id': typeof AppAdminPlansIdIndexRoute
  '/admin/assignments/$id/grade/$employeeId': typeof AppAdminAssignmentsIdGradeEmployeeIdRoute
  '/admin/assignments/$id/result/$employeeId': typeof AppAdminAssignmentsIdResultEmployeeIdRoute
  '/admin/assignments/$id/submit/$employeeId': typeof AppAdminAssignmentsIdSubmitEmployeeIdRoute
  '/admin/assignments/question-bank/$id/edit': typeof AppAdminAssignmentsQuestionBankIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/_app': typeof AppRouteWithChildren
  '/no-organization': typeof NoOrganizationRoute
  '/organizations': typeof OrganizationsRoute
  '/_app/analytic': typeof AppAnalyticRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/my-assignments': typeof AppMyAssignmentsRouteWithChildren
  '/_app/my-certificates': typeof AppMyCertificatesRoute
  '/_app/my-class': typeof AppMyClassRoute
  '/_app/my-favorites': typeof AppMyFavoritesRoute
  '/_app/my-flashcards': typeof AppMyFlashcardsRoute
  '/_app/my-gamification': typeof AppMyGamificationRoute
  '/_app/my-learning-paths': typeof AppMyLearningPathsRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_app/admin/certificates': typeof AppAdminCertificatesRouteWithChildren
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/gamifications': typeof AppAdminGamificationsRoute
  '/_app/branches/$id': typeof AppBranchesIdRoute
  '/_app/branches/list': typeof AppBranchesListRoute
  '/_app/class-room/$slug': typeof AppClassRoomSlugRouteWithChildren
  '/_app/departments/$id': typeof AppDepartmentsIdRoute
  '/_app/departments/list': typeof AppDepartmentsListRoute
  '/_app/student/dashboard': typeof AppStudentDashboardRoute
  '/surveys/$id/submit': typeof SurveysIdSubmitRouteWithChildren
  '/_app/branches/': typeof AppBranchesIndexRoute
  '/_app/departments/': typeof AppDepartmentsIndexRoute
  '/_app/admin/assignments/assigned': typeof AppAdminAssignmentsAssignedRoute
  '/_app/admin/assignments/question-bank': typeof AppAdminAssignmentsQuestionBankRouteWithChildren
  '/_app/admin/class-room/list': typeof AppAdminClassRoomListRoute
  '/_app/admin/employees/import': typeof AppAdminEmployeesImportRoute
  '/_app/admin/learning-paths/$id': typeof AppAdminLearningPathsIdRoute
  '/_app/admin/online-course/list': typeof AppAdminOnlineCourseListRoute
  '/_app/admin/plans/new': typeof AppAdminPlansNewRoute
  '/_app/admin/report/overview': typeof AppAdminReportOverviewRoute
  '/_app/admin/roles/$code': typeof AppAdminRolesCodeRoute
  '/_app/admin/surveys-results/$id': typeof AppAdminSurveysResultsIdRoute
  '/_app/admin/surveys/list': typeof AppAdminSurveysListRoute
  '/_app/my-learning-paths/learning-screen/$courseId': typeof AppMyLearningPathsLearningScreenCourseIdRoute
  '/_app/my-learning-paths/phase/$id': typeof AppMyLearningPathsPhaseIdRoute
  '/class-room/cd/$slug/$sessionId': typeof ClassRoomCdSlugSessionIdRoute
  '/surveys/$id/submit/thank-you': typeof SurveysIdSubmitThankYouRoute
  '/_app/admin/assignments/': typeof AppAdminAssignmentsIndexRoute
  '/_app/admin/class-room/': typeof AppAdminClassRoomIndexRoute
  '/_app/admin/employees/': typeof AppAdminEmployeesIndexRoute
  '/_app/admin/flashcards/': typeof AppAdminFlashcardsIndexRoute
  '/_app/admin/learning-paths/': typeof AppAdminLearningPathsIndexRoute
  '/_app/admin/online-course/': typeof AppAdminOnlineCourseIndexRoute
  '/_app/admin/plans/': typeof AppAdminPlansIndexRoute
  '/_app/admin/roles/': typeof AppAdminRolesIndexRoute
  '/_app/admin/surveys-results/': typeof AppAdminSurveysResultsIndexRoute
  '/_app/admin/surveys/': typeof AppAdminSurveysIndexRoute
  '/_app/admin/assignments/$id/assign': typeof AppAdminAssignmentsIdAssignRoute
  '/_app/admin/assignments/$id/students': typeof AppAdminAssignmentsIdStudentsRoute
  '/_app/admin/assignments/edit/$id': typeof AppAdminAssignmentsEditIdRoute
  '/_app/admin/certificates/edit/$id': typeof AppAdminCertificatesEditIdRoute
  '/_app/admin/class-room/$id/edit': typeof AppAdminClassRoomIdEditRoute
  '/_app/admin/class-room/$id/students': typeof AppAdminClassRoomIdStudentsRoute
  '/_app/admin/employees/$id/detail': typeof AppAdminEmployeesIdDetailRoute
  '/_app/admin/employees/$id/edit': typeof AppAdminEmployeesIdEditRoute
  '/_app/admin/flashcards/$id/edit': typeof AppAdminFlashcardsIdEditRoute
  '/_app/admin/learning-paths/edit/$id': typeof AppAdminLearningPathsEditIdRoute
  '/_app/admin/online-course/$id/edit': typeof AppAdminOnlineCourseIdEditRoute
  '/_app/admin/plans/$id/edit': typeof AppAdminPlansIdEditRoute
  '/_app/admin/surveys/$id/edit': typeof AppAdminSurveysIdEditRoute
  '/_app/admin/surveys/$id/statistics': typeof AppAdminSurveysIdStatisticsRoute
  '/_app/admin/surveys/$id/submissions': typeof AppAdminSurveysIdSubmissionsRoute
  '/_app/admin/surveys/$id/thank-you': typeof AppAdminSurveysIdThankYouRoute
  '/_app/class-room/$slug/learning-screen/$courseId': typeof AppClassRoomSlugLearningScreenCourseIdRoute
  '/_app/my-assignments/$id/result/$employeeId': typeof AppMyAssignmentsIdResultEmployeeIdRoute
  '/_app/my-assignments/$id/submit/$employeeId': typeof AppMyAssignmentsIdSubmitEmployeeIdRoute
  '/_app/admin/assignments/$id/': typeof AppAdminAssignmentsIdIndexRoute
  '/_app/admin/flashcards/$id/': typeof AppAdminFlashcardsIdIndexRoute
  '/_app/admin/online-course/$id/': typeof AppAdminOnlineCourseIdIndexRoute
  '/_app/admin/plans/$id/': typeof AppAdminPlansIdIndexRoute
  '/_app/admin/assignments/$id/grade/$employeeId': typeof AppAdminAssignmentsIdGradeEmployeeIdRoute
  '/_app/admin/assignments/$id/result/$employeeId': typeof AppAdminAssignmentsIdResultEmployeeIdRoute
  '/_app/admin/assignments/$id/submit/$employeeId': typeof AppAdminAssignmentsIdSubmitEmployeeIdRoute
  '/_app/admin/assignments/question-bank/$id/edit': typeof AppAdminAssignmentsQuestionBankIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/no-organization'
    | '/organizations'
    | '/analytic'
    | '/dashboard'
    | '/my-assignments'
    | '/my-certificates'
    | '/my-class'
    | '/my-favorites'
    | '/my-flashcards'
    | '/my-gamification'
    | '/my-learning-paths'
    | '/auth/error'
    | '/auth/signin'
    | '/auth/signup'
    | '/admin/certificates'
    | '/admin/dashboard'
    | '/admin/gamifications'
    | '/branches/$id'
    | '/branches/list'
    | '/class-room/$slug'
    | '/departments/$id'
    | '/departments/list'
    | '/student/dashboard'
    | '/surveys/$id/submit'
    | '/branches/'
    | '/departments/'
    | '/admin/assignments/assigned'
    | '/admin/assignments/question-bank'
    | '/admin/class-room/list'
    | '/admin/employees/import'
    | '/admin/learning-paths/$id'
    | '/admin/online-course/list'
    | '/admin/plans/new'
    | '/admin/report/overview'
    | '/admin/roles/$code'
    | '/admin/surveys-results/$id'
    | '/admin/surveys/list'
    | '/my-learning-paths/learning-screen/$courseId'
    | '/my-learning-paths/phase/$id'
    | '/class-room/cd/$slug/$sessionId'
    | '/surveys/$id/submit/thank-you'
    | '/admin/assignments/'
    | '/admin/class-room/'
    | '/admin/employees/'
    | '/admin/flashcards/'
    | '/admin/learning-paths/'
    | '/admin/online-course/'
    | '/admin/plans/'
    | '/admin/roles/'
    | '/admin/surveys-results/'
    | '/admin/surveys/'
    | '/admin/assignments/$id/assign'
    | '/admin/assignments/$id/students'
    | '/admin/assignments/edit/$id'
    | '/admin/certificates/edit/$id'
    | '/admin/class-room/$id/edit'
    | '/admin/class-room/$id/students'
    | '/admin/employees/$id/detail'
    | '/admin/employees/$id/edit'
    | '/admin/flashcards/$id/edit'
    | '/admin/learning-paths/edit/$id'
    | '/admin/online-course/$id/edit'
    | '/admin/plans/$id/edit'
    | '/admin/surveys/$id/edit'
    | '/admin/surveys/$id/statistics'
    | '/admin/surveys/$id/submissions'
    | '/admin/surveys/$id/thank-you'
    | '/class-room/$slug/learning-screen/$courseId'
    | '/my-assignments/$id/result/$employeeId'
    | '/my-assignments/$id/submit/$employeeId'
    | '/admin/assignments/$id/'
    | '/admin/flashcards/$id/'
    | '/admin/online-course/$id/'
    | '/admin/plans/$id/'
    | '/admin/assignments/$id/grade/$employeeId'
    | '/admin/assignments/$id/result/$employeeId'
    | '/admin/assignments/$id/submit/$employeeId'
    | '/admin/assignments/question-bank/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/no-organization'
    | '/organizations'
    | '/analytic'
    | '/dashboard'
    | '/my-assignments'
    | '/my-certificates'
    | '/my-class'
    | '/my-favorites'
    | '/my-flashcards'
    | '/my-gamification'
    | '/my-learning-paths'
    | '/auth/error'
    | '/auth/signin'
    | '/auth/signup'
    | '/admin/certificates'
    | '/admin/dashboard'
    | '/admin/gamifications'
    | '/branches/$id'
    | '/branches/list'
    | '/class-room/$slug'
    | '/departments/$id'
    | '/departments/list'
    | '/student/dashboard'
    | '/surveys/$id/submit'
    | '/branches'
    | '/departments'
    | '/admin/assignments/assigned'
    | '/admin/assignments/question-bank'
    | '/admin/class-room/list'
    | '/admin/employees/import'
    | '/admin/learning-paths/$id'
    | '/admin/online-course/list'
    | '/admin/plans/new'
    | '/admin/report/overview'
    | '/admin/roles/$code'
    | '/admin/surveys-results/$id'
    | '/admin/surveys/list'
    | '/my-learning-paths/learning-screen/$courseId'
    | '/my-learning-paths/phase/$id'
    | '/class-room/cd/$slug/$sessionId'
    | '/surveys/$id/submit/thank-you'
    | '/admin/assignments'
    | '/admin/class-room'
    | '/admin/employees'
    | '/admin/flashcards'
    | '/admin/learning-paths'
    | '/admin/online-course'
    | '/admin/plans'
    | '/admin/roles'
    | '/admin/surveys-results'
    | '/admin/surveys'
    | '/admin/assignments/$id/assign'
    | '/admin/assignments/$id/students'
    | '/admin/assignments/edit/$id'
    | '/admin/certificates/edit/$id'
    | '/admin/class-room/$id/edit'
    | '/admin/class-room/$id/students'
    | '/admin/employees/$id/detail'
    | '/admin/employees/$id/edit'
    | '/admin/flashcards/$id/edit'
    | '/admin/learning-paths/edit/$id'
    | '/admin/online-course/$id/edit'
    | '/admin/plans/$id/edit'
    | '/admin/surveys/$id/edit'
    | '/admin/surveys/$id/statistics'
    | '/admin/surveys/$id/submissions'
    | '/admin/surveys/$id/thank-you'
    | '/class-room/$slug/learning-screen/$courseId'
    | '/my-assignments/$id/result/$employeeId'
    | '/my-assignments/$id/submit/$employeeId'
    | '/admin/assignments/$id'
    | '/admin/flashcards/$id'
    | '/admin/online-course/$id'
    | '/admin/plans/$id'
    | '/admin/assignments/$id/grade/$employeeId'
    | '/admin/assignments/$id/result/$employeeId'
    | '/admin/assignments/$id/submit/$employeeId'
    | '/admin/assignments/question-bank/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_app'
    | '/no-organization'
    | '/organizations'
    | '/_app/analytic'
    | '/_app/dashboard'
    | '/_app/my-assignments'
    | '/_app/my-certificates'
    | '/_app/my-class'
    | '/_app/my-favorites'
    | '/_app/my-flashcards'
    | '/_app/my-gamification'
    | '/_app/my-learning-paths'
    | '/auth/error'
    | '/auth/signin'
    | '/auth/signup'
    | '/_app/admin/certificates'
    | '/_app/admin/dashboard'
    | '/_app/admin/gamifications'
    | '/_app/branches/$id'
    | '/_app/branches/list'
    | '/_app/class-room/$slug'
    | '/_app/departments/$id'
    | '/_app/departments/list'
    | '/_app/student/dashboard'
    | '/surveys/$id/submit'
    | '/_app/branches/'
    | '/_app/departments/'
    | '/_app/admin/assignments/assigned'
    | '/_app/admin/assignments/question-bank'
    | '/_app/admin/class-room/list'
    | '/_app/admin/employees/import'
    | '/_app/admin/learning-paths/$id'
    | '/_app/admin/online-course/list'
    | '/_app/admin/plans/new'
    | '/_app/admin/report/overview'
    | '/_app/admin/roles/$code'
    | '/_app/admin/surveys-results/$id'
    | '/_app/admin/surveys/list'
    | '/_app/my-learning-paths/learning-screen/$courseId'
    | '/_app/my-learning-paths/phase/$id'
    | '/class-room/cd/$slug/$sessionId'
    | '/surveys/$id/submit/thank-you'
    | '/_app/admin/assignments/'
    | '/_app/admin/class-room/'
    | '/_app/admin/employees/'
    | '/_app/admin/flashcards/'
    | '/_app/admin/learning-paths/'
    | '/_app/admin/online-course/'
    | '/_app/admin/plans/'
    | '/_app/admin/roles/'
    | '/_app/admin/surveys-results/'
    | '/_app/admin/surveys/'
    | '/_app/admin/assignments/$id/assign'
    | '/_app/admin/assignments/$id/students'
    | '/_app/admin/assignments/edit/$id'
    | '/_app/admin/certificates/edit/$id'
    | '/_app/admin/class-room/$id/edit'
    | '/_app/admin/class-room/$id/students'
    | '/_app/admin/employees/$id/detail'
    | '/_app/admin/employees/$id/edit'
    | '/_app/admin/flashcards/$id/edit'
    | '/_app/admin/learning-paths/edit/$id'
    | '/_app/admin/online-course/$id/edit'
    | '/_app/admin/plans/$id/edit'
    | '/_app/admin/surveys/$id/edit'
    | '/_app/admin/surveys/$id/statistics'
    | '/_app/admin/surveys/$id/submissions'
    | '/_app/admin/surveys/$id/thank-you'
    | '/_app/class-room/$slug/learning-screen/$courseId'
    | '/_app/my-assignments/$id/result/$employeeId'
    | '/_app/my-assignments/$id/submit/$employeeId'
    | '/_app/admin/assignments/$id/'
    | '/_app/admin/flashcards/$id/'
    | '/_app/admin/online-course/$id/'
    | '/_app/admin/plans/$id/'
    | '/_app/admin/assignments/$id/grade/$employeeId'
    | '/_app/admin/assignments/$id/result/$employeeId'
    | '/_app/admin/assignments/$id/submit/$employeeId'
    | '/_app/admin/assignments/question-bank/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AppRoute: typeof AppRouteWithChildren
  NoOrganizationRoute: typeof NoOrganizationRoute
  OrganizationsRoute: typeof OrganizationsRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  SurveysIdSubmitRoute: typeof SurveysIdSubmitRouteWithChildren
  ClassRoomCdSlugSessionIdRoute: typeof ClassRoomCdSlugSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-organization': {
      id: '/no-organization'
      path: '/no-organization'
      fullPath: '/no-organization'
      preLoaderRoute: typeof NoOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/my-learning-paths': {
      id: '/_app/my-learning-paths'
      path: '/my-learning-paths'
      fullPath: '/my-learning-paths'
      preLoaderRoute: typeof AppMyLearningPathsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-gamification': {
      id: '/_app/my-gamification'
      path: '/my-gamification'
      fullPath: '/my-gamification'
      preLoaderRoute: typeof AppMyGamificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-flashcards': {
      id: '/_app/my-flashcards'
      path: '/my-flashcards'
      fullPath: '/my-flashcards'
      preLoaderRoute: typeof AppMyFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-favorites': {
      id: '/_app/my-favorites'
      path: '/my-favorites'
      fullPath: '/my-favorites'
      preLoaderRoute: typeof AppMyFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-class': {
      id: '/_app/my-class'
      path: '/my-class'
      fullPath: '/my-class'
      preLoaderRoute: typeof AppMyClassRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-certificates': {
      id: '/_app/my-certificates'
      path: '/my-certificates'
      fullPath: '/my-certificates'
      preLoaderRoute: typeof AppMyCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-assignments': {
      id: '/_app/my-assignments'
      path: '/my-assignments'
      fullPath: '/my-assignments'
      preLoaderRoute: typeof AppMyAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytic': {
      id: '/_app/analytic'
      path: '/analytic'
      fullPath: '/analytic'
      preLoaderRoute: typeof AppAnalyticRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/': {
      id: '/_app/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof AppDepartmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches/': {
      id: '/_app/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof AppBranchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/surveys/$id/submit': {
      id: '/surveys/$id/submit'
      path: '/surveys/$id/submit'
      fullPath: '/surveys/$id/submit'
      preLoaderRoute: typeof SurveysIdSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/student/dashboard': {
      id: '/_app/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AppStudentDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/list': {
      id: '/_app/departments/list'
      path: '/departments/list'
      fullPath: '/departments/list'
      preLoaderRoute: typeof AppDepartmentsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/$id': {
      id: '/_app/departments/$id'
      path: '/departments/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof AppDepartmentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/class-room/$slug': {
      id: '/_app/class-room/$slug'
      path: '/class-room/$slug'
      fullPath: '/class-room/$slug'
      preLoaderRoute: typeof AppClassRoomSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches/list': {
      id: '/_app/branches/list'
      path: '/branches/list'
      fullPath: '/branches/list'
      preLoaderRoute: typeof AppBranchesListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches/$id': {
      id: '/_app/branches/$id'
      path: '/branches/$id'
      fullPath: '/branches/$id'
      preLoaderRoute: typeof AppBranchesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/gamifications': {
      id: '/_app/admin/gamifications'
      path: '/admin/gamifications'
      fullPath: '/admin/gamifications'
      preLoaderRoute: typeof AppAdminGamificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/certificates': {
      id: '/_app/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AppAdminCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/surveys/': {
      id: '/_app/admin/surveys/'
      path: '/admin/surveys'
      fullPath: '/admin/surveys/'
      preLoaderRoute: typeof AppAdminSurveysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/surveys-results/': {
      id: '/_app/admin/surveys-results/'
      path: '/admin/surveys-results'
      fullPath: '/admin/surveys-results/'
      preLoaderRoute: typeof AppAdminSurveysResultsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles/': {
      id: '/_app/admin/roles/'
      path: '/admin/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AppAdminRolesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/plans/': {
      id: '/_app/admin/plans/'
      path: '/admin/plans'
      fullPath: '/admin/plans/'
      preLoaderRoute: typeof AppAdminPlansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/online-course/': {
      id: '/_app/admin/online-course/'
      path: '/admin/online-course'
      fullPath: '/admin/online-course/'
      preLoaderRoute: typeof AppAdminOnlineCourseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/learning-paths/': {
      id: '/_app/admin/learning-paths/'
      path: '/admin/learning-paths'
      fullPath: '/admin/learning-paths/'
      preLoaderRoute: typeof AppAdminLearningPathsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/flashcards/': {
      id: '/_app/admin/flashcards/'
      path: '/admin/flashcards'
      fullPath: '/admin/flashcards/'
      preLoaderRoute: typeof AppAdminFlashcardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/employees/': {
      id: '/_app/admin/employees/'
      path: '/admin/employees'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AppAdminEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/class-room/': {
      id: '/_app/admin/class-room/'
      path: '/admin/class-room'
      fullPath: '/admin/class-room/'
      preLoaderRoute: typeof AppAdminClassRoomIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/assignments/': {
      id: '/_app/admin/assignments/'
      path: '/admin/assignments'
      fullPath: '/admin/assignments/'
      preLoaderRoute: typeof AppAdminAssignmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/surveys/$id/submit/thank-you': {
      id: '/surveys/$id/submit/thank-you'
      path: '/thank-you'
      fullPath: '/surveys/$id/submit/thank-you'
      preLoaderRoute: typeof SurveysIdSubmitThankYouRouteImport
      parentRoute: typeof SurveysIdSubmitRoute
    }
    '/class-room/cd/$slug/$sessionId': {
      id: '/class-room/cd/$slug/$sessionId'
      path: '/class-room/cd/$slug/$sessionId'
      fullPath: '/class-room/cd/$slug/$sessionId'
      preLoaderRoute: typeof ClassRoomCdSlugSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/my-learning-paths/phase/$id': {
      id: '/_app/my-learning-paths/phase/$id'
      path: '/phase/$id'
      fullPath: '/my-learning-paths/phase/$id'
      preLoaderRoute: typeof AppMyLearningPathsPhaseIdRouteImport
      parentRoute: typeof AppMyLearningPathsRoute
    }
    '/_app/my-learning-paths/learning-screen/$courseId': {
      id: '/_app/my-learning-paths/learning-screen/$courseId'
      path: '/learning-screen/$courseId'
      fullPath: '/my-learning-paths/learning-screen/$courseId'
      preLoaderRoute: typeof AppMyLearningPathsLearningScreenCourseIdRouteImport
      parentRoute: typeof AppMyLearningPathsRoute
    }
    '/_app/admin/surveys/list': {
      id: '/_app/admin/surveys/list'
      path: '/admin/surveys/list'
      fullPath: '/admin/surveys/list'
      preLoaderRoute: typeof AppAdminSurveysListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/surveys-results/$id': {
      id: '/_app/admin/surveys-results/$id'
      path: '/admin/surveys-results/$id'
      fullPath: '/admin/surveys-results/$id'
      preLoaderRoute: typeof AppAdminSurveysResultsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles/$code': {
      id: '/_app/admin/roles/$code'
      path: '/admin/roles/$code'
      fullPath: '/admin/roles/$code'
      preLoaderRoute: typeof AppAdminRolesCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/report/overview': {
      id: '/_app/admin/report/overview'
      path: '/admin/report/overview'
      fullPath: '/admin/report/overview'
      preLoaderRoute: typeof AppAdminReportOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/plans/new': {
      id: '/_app/admin/plans/new'
      path: '/admin/plans/new'
      fullPath: '/admin/plans/new'
      preLoaderRoute: typeof AppAdminPlansNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/online-course/list': {
      id: '/_app/admin/online-course/list'
      path: '/admin/online-course/list'
      fullPath: '/admin/online-course/list'
      preLoaderRoute: typeof AppAdminOnlineCourseListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/learning-paths/$id': {
      id: '/_app/admin/learning-paths/$id'
      path: '/admin/learning-paths/$id'
      fullPath: '/admin/learning-paths/$id'
      preLoaderRoute: typeof AppAdminLearningPathsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/employees/import': {
      id: '/_app/admin/employees/import'
      path: '/admin/employees/import'
      fullPath: '/admin/employees/import'
      preLoaderRoute: typeof AppAdminEmployeesImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/class-room/list': {
      id: '/_app/admin/class-room/list'
      path: '/admin/class-room/list'
      fullPath: '/admin/class-room/list'
      preLoaderRoute: typeof AppAdminClassRoomListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/assignments/question-bank': {
      id: '/_app/admin/assignments/question-bank'
      path: '/admin/assignments/question-bank'
      fullPath: '/admin/assignments/question-bank'
      preLoaderRoute: typeof AppAdminAssignmentsQuestionBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/assignments/assigned': {
      id: '/_app/admin/assignments/assigned'
      path: '/admin/assignments/assigned'
      fullPath: '/admin/assignments/assigned'
      preLoaderRoute: typeof AppAdminAssignmentsAssignedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/plans/$id/': {
      id: '/_app/admin/plans/$id/'
      path: '/admin/plans/$id'
      fullPath: '/admin/plans/$id/'
      preLoaderRoute: typeof AppAdminPlansIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/online-course/$id/': {
      id: '/_app/admin/online-course/$id/'
      path: '/admin/online-course/$id'
      fullPath: '/admin/online-course/$id/'
      preLoaderRoute: typeof AppAdminOnlineCourseIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/flashcards/$id/': {
      id: '/_app/admin/flashcards/$id/'
      path: '/admin/flashcards/$id'
      fullPath: '/admin/flashcards/$id/'
      preLoaderRoute: typeof AppAdminFlashcardsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/assignments/$id/': {
      id: '/_app/admin/assignments/$id/'
      path: '/admin/assignments/$id'
      fullPath: '/admin/assignments/$id/'
      preLoaderRoute: typeof AppAdminAssignmentsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-assignments/$id/submit/$employeeId': {
      id: '/_app/my-assignments/$id/submit/$employeeId'
      path: '/$id/submit/$employeeId'
      fullPath: '/my-assignments/$id/submit/$employeeId'
      preLoaderRoute: typeof AppMyAssignmentsIdSubmitEmployeeIdRouteImport
      parentRoute: typeof AppMyAssignmentsRoute
    }
    '/_app/my-assignments/$id/result/$employeeId': {
      id: '/_app/my-assignments/$id/result/$employeeId'
      path: '/$id/result/$employeeId'
      fullPath: '/my-assignments/$id/result/$employeeId'
      preLoaderRoute: typeof AppMyAssignmentsIdResultEmployeeIdRouteImport
      parentRoute: typeof AppMyAssignmentsRoute
    }
    '/_app/class-room/$slug/learning-screen/$courseId': {
      id: '/_app/class-room/$slug/learning-screen/$courseId'
      path: '/learning-screen/$courseId'
      fullPath: '/class-room/$slug/learning-screen/$courseId'
      preLoaderRoute: typeof AppClassRoomSlugLearningScreenCourseIdRouteImport
      parentRoute: typeof AppClassRoomSlugRoute
    }
    '/_app/admin/surveys/$id/thank-you': {
      id: '/_app/admin/surveys/$id/thank-you'
      path: '/admin/surveys/$id/thank-you'
      fullPath: '/admin/surveys/$id/thank-you'
      preLoaderRoute: typeof AppAdminSurveysIdThankYouRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/surveys/$id/submissions': {
      id: '/_app/admin/surveys/$id/submissions'
      path: '/admin/surveys/$id/submissions'
      fullPath: '/admin/surveys/$id/submissions'
      preLoaderRoute: typeof AppAdminSurveysIdSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/surveys/$id/statistics': {
      id: '/_app/admin/surveys/$id/statistics'
      path: '/admin/surveys/$id/statistics'
      fullPath: '/admin/surveys/$id/statistics'
      preLoaderRoute: typeof AppAdminSurveysIdStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/surveys/$id/edit': {
      id: '/_app/admin/surveys/$id/edit'
      path: '/admin/surveys/$id/edit'
      fullPath: '/admin/surveys/$id/edit'
      preLoaderRoute: typeof AppAdminSurveysIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/plans/$id/edit': {
      id: '/_app/admin/plans/$id/edit'
      path: '/admin/plans/$id/edit'
      fullPath: '/admin/plans/$id/edit'
      preLoaderRoute: typeof AppAdminPlansIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/online-course/$id/edit': {
      id: '/_app/admin/online-course/$id/edit'
      path: '/admin/online-course/$id/edit'
      fullPath: '/admin/online-course/$id/edit'
      preLoaderRoute: typeof AppAdminOnlineCourseIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/learning-paths/edit/$id': {
      id: '/_app/admin/learning-paths/edit/$id'
      path: '/admin/learning-paths/edit/$id'
      fullPath: '/admin/learning-paths/edit/$id'
      preLoaderRoute: typeof AppAdminLearningPathsEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/flashcards/$id/edit': {
      id: '/_app/admin/flashcards/$id/edit'
      path: '/admin/flashcards/$id/edit'
      fullPath: '/admin/flashcards/$id/edit'
      preLoaderRoute: typeof AppAdminFlashcardsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/employees/$id/edit': {
      id: '/_app/admin/employees/$id/edit'
      path: '/admin/employees/$id/edit'
      fullPath: '/admin/employees/$id/edit'
      preLoaderRoute: typeof AppAdminEmployeesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/employees/$id/detail': {
      id: '/_app/admin/employees/$id/detail'
      path: '/admin/employees/$id/detail'
      fullPath: '/admin/employees/$id/detail'
      preLoaderRoute: typeof AppAdminEmployeesIdDetailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/class-room/$id/students': {
      id: '/_app/admin/class-room/$id/students'
      path: '/admin/class-room/$id/students'
      fullPath: '/admin/class-room/$id/students'
      preLoaderRoute: typeof AppAdminClassRoomIdStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/class-room/$id/edit': {
      id: '/_app/admin/class-room/$id/edit'
      path: '/admin/class-room/$id/edit'
      fullPath: '/admin/class-room/$id/edit'
      preLoaderRoute: typeof AppAdminClassRoomIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/certificates/edit/$id': {
      id: '/_app/admin/certificates/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/certificates/edit/$id'
      preLoaderRoute: typeof AppAdminCertificatesEditIdRouteImport
      parentRoute: typeof AppAdminCertificatesRoute
    }
    '/_app/admin/assignments/edit/$id': {
      id: '/_app/admin/assignments/edit/$id'
      path: '/admin/assignments/edit/$id'
      fullPath: '/admin/assignments/edit/$id'
      preLoaderRoute: typeof AppAdminAssignmentsEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/assignments/$id/students': {
      id: '/_app/admin/assignments/$id/students'
      path: '/admin/assignments/$id/students'
      fullPath: '/admin/assignments/$id/students'
      preLoaderRoute: typeof AppAdminAssignmentsIdStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/assignments/$id/assign': {
      id: '/_app/admin/assignments/$id/assign'
      path: '/admin/assignments/$id/assign'
      fullPath: '/admin/assignments/$id/assign'
      preLoaderRoute: typeof AppAdminAssignmentsIdAssignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/assignments/question-bank/$id/edit': {
      id: '/_app/admin/assignments/question-bank/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/assignments/question-bank/$id/edit'
      preLoaderRoute: typeof AppAdminAssignmentsQuestionBankIdEditRouteImport
      parentRoute: typeof AppAdminAssignmentsQuestionBankRoute
    }
    '/_app/admin/assignments/$id/submit/$employeeId': {
      id: '/_app/admin/assignments/$id/submit/$employeeId'
      path: '/admin/assignments/$id/submit/$employeeId'
      fullPath: '/admin/assignments/$id/submit/$employeeId'
      preLoaderRoute: typeof AppAdminAssignmentsIdSubmitEmployeeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/assignments/$id/result/$employeeId': {
      id: '/_app/admin/assignments/$id/result/$employeeId'
      path: '/admin/assignments/$id/result/$employeeId'
      fullPath: '/admin/assignments/$id/result/$employeeId'
      preLoaderRoute: typeof AppAdminAssignmentsIdResultEmployeeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/assignments/$id/grade/$employeeId': {
      id: '/_app/admin/assignments/$id/grade/$employeeId'
      path: '/admin/assignments/$id/grade/$employeeId'
      fullPath: '/admin/assignments/$id/grade/$employeeId'
      preLoaderRoute: typeof AppAdminAssignmentsIdGradeEmployeeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppMyAssignmentsRouteChildren {
  AppMyAssignmentsIdResultEmployeeIdRoute: typeof AppMyAssignmentsIdResultEmployeeIdRoute
  AppMyAssignmentsIdSubmitEmployeeIdRoute: typeof AppMyAssignmentsIdSubmitEmployeeIdRoute
}

const AppMyAssignmentsRouteChildren: AppMyAssignmentsRouteChildren = {
  AppMyAssignmentsIdResultEmployeeIdRoute:
    AppMyAssignmentsIdResultEmployeeIdRoute,
  AppMyAssignmentsIdSubmitEmployeeIdRoute:
    AppMyAssignmentsIdSubmitEmployeeIdRoute,
}

const AppMyAssignmentsRouteWithChildren =
  AppMyAssignmentsRoute._addFileChildren(AppMyAssignmentsRouteChildren)

interface AppMyLearningPathsRouteChildren {
  AppMyLearningPathsLearningScreenCourseIdRoute: typeof AppMyLearningPathsLearningScreenCourseIdRoute
  AppMyLearningPathsPhaseIdRoute: typeof AppMyLearningPathsPhaseIdRoute
}

const AppMyLearningPathsRouteChildren: AppMyLearningPathsRouteChildren = {
  AppMyLearningPathsLearningScreenCourseIdRoute:
    AppMyLearningPathsLearningScreenCourseIdRoute,
  AppMyLearningPathsPhaseIdRoute: AppMyLearningPathsPhaseIdRoute,
}

const AppMyLearningPathsRouteWithChildren =
  AppMyLearningPathsRoute._addFileChildren(AppMyLearningPathsRouteChildren)

interface AppAdminCertificatesRouteChildren {
  AppAdminCertificatesEditIdRoute: typeof AppAdminCertificatesEditIdRoute
}

const AppAdminCertificatesRouteChildren: AppAdminCertificatesRouteChildren = {
  AppAdminCertificatesEditIdRoute: AppAdminCertificatesEditIdRoute,
}

const AppAdminCertificatesRouteWithChildren =
  AppAdminCertificatesRoute._addFileChildren(AppAdminCertificatesRouteChildren)

interface AppClassRoomSlugRouteChildren {
  AppClassRoomSlugLearningScreenCourseIdRoute: typeof AppClassRoomSlugLearningScreenCourseIdRoute
}

const AppClassRoomSlugRouteChildren: AppClassRoomSlugRouteChildren = {
  AppClassRoomSlugLearningScreenCourseIdRoute:
    AppClassRoomSlugLearningScreenCourseIdRoute,
}

const AppClassRoomSlugRouteWithChildren =
  AppClassRoomSlugRoute._addFileChildren(AppClassRoomSlugRouteChildren)

interface AppAdminAssignmentsQuestionBankRouteChildren {
  AppAdminAssignmentsQuestionBankIdEditRoute: typeof AppAdminAssignmentsQuestionBankIdEditRoute
}

const AppAdminAssignmentsQuestionBankRouteChildren: AppAdminAssignmentsQuestionBankRouteChildren =
  {
    AppAdminAssignmentsQuestionBankIdEditRoute:
      AppAdminAssignmentsQuestionBankIdEditRoute,
  }

const AppAdminAssignmentsQuestionBankRouteWithChildren =
  AppAdminAssignmentsQuestionBankRoute._addFileChildren(
    AppAdminAssignmentsQuestionBankRouteChildren,
  )

interface AppRouteChildren {
  AppAnalyticRoute: typeof AppAnalyticRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMyAssignmentsRoute: typeof AppMyAssignmentsRouteWithChildren
  AppMyCertificatesRoute: typeof AppMyCertificatesRoute
  AppMyClassRoute: typeof AppMyClassRoute
  AppMyFavoritesRoute: typeof AppMyFavoritesRoute
  AppMyFlashcardsRoute: typeof AppMyFlashcardsRoute
  AppMyGamificationRoute: typeof AppMyGamificationRoute
  AppMyLearningPathsRoute: typeof AppMyLearningPathsRouteWithChildren
  AppAdminCertificatesRoute: typeof AppAdminCertificatesRouteWithChildren
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminGamificationsRoute: typeof AppAdminGamificationsRoute
  AppBranchesIdRoute: typeof AppBranchesIdRoute
  AppBranchesListRoute: typeof AppBranchesListRoute
  AppClassRoomSlugRoute: typeof AppClassRoomSlugRouteWithChildren
  AppDepartmentsIdRoute: typeof AppDepartmentsIdRoute
  AppDepartmentsListRoute: typeof AppDepartmentsListRoute
  AppStudentDashboardRoute: typeof AppStudentDashboardRoute
  AppBranchesIndexRoute: typeof AppBranchesIndexRoute
  AppDepartmentsIndexRoute: typeof AppDepartmentsIndexRoute
  AppAdminAssignmentsAssignedRoute: typeof AppAdminAssignmentsAssignedRoute
  AppAdminAssignmentsQuestionBankRoute: typeof AppAdminAssignmentsQuestionBankRouteWithChildren
  AppAdminClassRoomListRoute: typeof AppAdminClassRoomListRoute
  AppAdminEmployeesImportRoute: typeof AppAdminEmployeesImportRoute
  AppAdminLearningPathsIdRoute: typeof AppAdminLearningPathsIdRoute
  AppAdminOnlineCourseListRoute: typeof AppAdminOnlineCourseListRoute
  AppAdminPlansNewRoute: typeof AppAdminPlansNewRoute
  AppAdminReportOverviewRoute: typeof AppAdminReportOverviewRoute
  AppAdminRolesCodeRoute: typeof AppAdminRolesCodeRoute
  AppAdminSurveysResultsIdRoute: typeof AppAdminSurveysResultsIdRoute
  AppAdminSurveysListRoute: typeof AppAdminSurveysListRoute
  AppAdminAssignmentsIndexRoute: typeof AppAdminAssignmentsIndexRoute
  AppAdminClassRoomIndexRoute: typeof AppAdminClassRoomIndexRoute
  AppAdminEmployeesIndexRoute: typeof AppAdminEmployeesIndexRoute
  AppAdminFlashcardsIndexRoute: typeof AppAdminFlashcardsIndexRoute
  AppAdminLearningPathsIndexRoute: typeof AppAdminLearningPathsIndexRoute
  AppAdminOnlineCourseIndexRoute: typeof AppAdminOnlineCourseIndexRoute
  AppAdminPlansIndexRoute: typeof AppAdminPlansIndexRoute
  AppAdminRolesIndexRoute: typeof AppAdminRolesIndexRoute
  AppAdminSurveysResultsIndexRoute: typeof AppAdminSurveysResultsIndexRoute
  AppAdminSurveysIndexRoute: typeof AppAdminSurveysIndexRoute
  AppAdminAssignmentsIdAssignRoute: typeof AppAdminAssignmentsIdAssignRoute
  AppAdminAssignmentsIdStudentsRoute: typeof AppAdminAssignmentsIdStudentsRoute
  AppAdminAssignmentsEditIdRoute: typeof AppAdminAssignmentsEditIdRoute
  AppAdminClassRoomIdEditRoute: typeof AppAdminClassRoomIdEditRoute
  AppAdminClassRoomIdStudentsRoute: typeof AppAdminClassRoomIdStudentsRoute
  AppAdminEmployeesIdDetailRoute: typeof AppAdminEmployeesIdDetailRoute
  AppAdminEmployeesIdEditRoute: typeof AppAdminEmployeesIdEditRoute
  AppAdminFlashcardsIdEditRoute: typeof AppAdminFlashcardsIdEditRoute
  AppAdminLearningPathsEditIdRoute: typeof AppAdminLearningPathsEditIdRoute
  AppAdminOnlineCourseIdEditRoute: typeof AppAdminOnlineCourseIdEditRoute
  AppAdminPlansIdEditRoute: typeof AppAdminPlansIdEditRoute
  AppAdminSurveysIdEditRoute: typeof AppAdminSurveysIdEditRoute
  AppAdminSurveysIdStatisticsRoute: typeof AppAdminSurveysIdStatisticsRoute
  AppAdminSurveysIdSubmissionsRoute: typeof AppAdminSurveysIdSubmissionsRoute
  AppAdminSurveysIdThankYouRoute: typeof AppAdminSurveysIdThankYouRoute
  AppAdminAssignmentsIdIndexRoute: typeof AppAdminAssignmentsIdIndexRoute
  AppAdminFlashcardsIdIndexRoute: typeof AppAdminFlashcardsIdIndexRoute
  AppAdminOnlineCourseIdIndexRoute: typeof AppAdminOnlineCourseIdIndexRoute
  AppAdminPlansIdIndexRoute: typeof AppAdminPlansIdIndexRoute
  AppAdminAssignmentsIdGradeEmployeeIdRoute: typeof AppAdminAssignmentsIdGradeEmployeeIdRoute
  AppAdminAssignmentsIdResultEmployeeIdRoute: typeof AppAdminAssignmentsIdResultEmployeeIdRoute
  AppAdminAssignmentsIdSubmitEmployeeIdRoute: typeof AppAdminAssignmentsIdSubmitEmployeeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticRoute: AppAnalyticRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMyAssignmentsRoute: AppMyAssignmentsRouteWithChildren,
  AppMyCertificatesRoute: AppMyCertificatesRoute,
  AppMyClassRoute: AppMyClassRoute,
  AppMyFavoritesRoute: AppMyFavoritesRoute,
  AppMyFlashcardsRoute: AppMyFlashcardsRoute,
  AppMyGamificationRoute: AppMyGamificationRoute,
  AppMyLearningPathsRoute: AppMyLearningPathsRouteWithChildren,
  AppAdminCertificatesRoute: AppAdminCertificatesRouteWithChildren,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminGamificationsRoute: AppAdminGamificationsRoute,
  AppBranchesIdRoute: AppBranchesIdRoute,
  AppBranchesListRoute: AppBranchesListRoute,
  AppClassRoomSlugRoute: AppClassRoomSlugRouteWithChildren,
  AppDepartmentsIdRoute: AppDepartmentsIdRoute,
  AppDepartmentsListRoute: AppDepartmentsListRoute,
  AppStudentDashboardRoute: AppStudentDashboardRoute,
  AppBranchesIndexRoute: AppBranchesIndexRoute,
  AppDepartmentsIndexRoute: AppDepartmentsIndexRoute,
  AppAdminAssignmentsAssignedRoute: AppAdminAssignmentsAssignedRoute,
  AppAdminAssignmentsQuestionBankRoute:
    AppAdminAssignmentsQuestionBankRouteWithChildren,
  AppAdminClassRoomListRoute: AppAdminClassRoomListRoute,
  AppAdminEmployeesImportRoute: AppAdminEmployeesImportRoute,
  AppAdminLearningPathsIdRoute: AppAdminLearningPathsIdRoute,
  AppAdminOnlineCourseListRoute: AppAdminOnlineCourseListRoute,
  AppAdminPlansNewRoute: AppAdminPlansNewRoute,
  AppAdminReportOverviewRoute: AppAdminReportOverviewRoute,
  AppAdminRolesCodeRoute: AppAdminRolesCodeRoute,
  AppAdminSurveysResultsIdRoute: AppAdminSurveysResultsIdRoute,
  AppAdminSurveysListRoute: AppAdminSurveysListRoute,
  AppAdminAssignmentsIndexRoute: AppAdminAssignmentsIndexRoute,
  AppAdminClassRoomIndexRoute: AppAdminClassRoomIndexRoute,
  AppAdminEmployeesIndexRoute: AppAdminEmployeesIndexRoute,
  AppAdminFlashcardsIndexRoute: AppAdminFlashcardsIndexRoute,
  AppAdminLearningPathsIndexRoute: AppAdminLearningPathsIndexRoute,
  AppAdminOnlineCourseIndexRoute: AppAdminOnlineCourseIndexRoute,
  AppAdminPlansIndexRoute: AppAdminPlansIndexRoute,
  AppAdminRolesIndexRoute: AppAdminRolesIndexRoute,
  AppAdminSurveysResultsIndexRoute: AppAdminSurveysResultsIndexRoute,
  AppAdminSurveysIndexRoute: AppAdminSurveysIndexRoute,
  AppAdminAssignmentsIdAssignRoute: AppAdminAssignmentsIdAssignRoute,
  AppAdminAssignmentsIdStudentsRoute: AppAdminAssignmentsIdStudentsRoute,
  AppAdminAssignmentsEditIdRoute: AppAdminAssignmentsEditIdRoute,
  AppAdminClassRoomIdEditRoute: AppAdminClassRoomIdEditRoute,
  AppAdminClassRoomIdStudentsRoute: AppAdminClassRoomIdStudentsRoute,
  AppAdminEmployeesIdDetailRoute: AppAdminEmployeesIdDetailRoute,
  AppAdminEmployeesIdEditRoute: AppAdminEmployeesIdEditRoute,
  AppAdminFlashcardsIdEditRoute: AppAdminFlashcardsIdEditRoute,
  AppAdminLearningPathsEditIdRoute: AppAdminLearningPathsEditIdRoute,
  AppAdminOnlineCourseIdEditRoute: AppAdminOnlineCourseIdEditRoute,
  AppAdminPlansIdEditRoute: AppAdminPlansIdEditRoute,
  AppAdminSurveysIdEditRoute: AppAdminSurveysIdEditRoute,
  AppAdminSurveysIdStatisticsRoute: AppAdminSurveysIdStatisticsRoute,
  AppAdminSurveysIdSubmissionsRoute: AppAdminSurveysIdSubmissionsRoute,
  AppAdminSurveysIdThankYouRoute: AppAdminSurveysIdThankYouRoute,
  AppAdminAssignmentsIdIndexRoute: AppAdminAssignmentsIdIndexRoute,
  AppAdminFlashcardsIdIndexRoute: AppAdminFlashcardsIdIndexRoute,
  AppAdminOnlineCourseIdIndexRoute: AppAdminOnlineCourseIdIndexRoute,
  AppAdminPlansIdIndexRoute: AppAdminPlansIdIndexRoute,
  AppAdminAssignmentsIdGradeEmployeeIdRoute:
    AppAdminAssignmentsIdGradeEmployeeIdRoute,
  AppAdminAssignmentsIdResultEmployeeIdRoute:
    AppAdminAssignmentsIdResultEmployeeIdRoute,
  AppAdminAssignmentsIdSubmitEmployeeIdRoute:
    AppAdminAssignmentsIdSubmitEmployeeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SurveysIdSubmitRouteChildren {
  SurveysIdSubmitThankYouRoute: typeof SurveysIdSubmitThankYouRoute
}

const SurveysIdSubmitRouteChildren: SurveysIdSubmitRouteChildren = {
  SurveysIdSubmitThankYouRoute: SurveysIdSubmitThankYouRoute,
}

const SurveysIdSubmitRouteWithChildren = SurveysIdSubmitRoute._addFileChildren(
  SurveysIdSubmitRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AppRoute: AppRouteWithChildren,
  NoOrganizationRoute: NoOrganizationRoute,
  OrganizationsRoute: OrganizationsRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  SurveysIdSubmitRoute: SurveysIdSubmitRouteWithChildren,
  ClassRoomCdSlugSessionIdRoute: ClassRoomCdSlugSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
