name: TriggerCIDev

on:
  push:
    branches: ["dev", "staging", "main"]
  pull_request:
    branches: ["dev", "staging","main"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          
      - name: Setup SSH Agent and Add Key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          
      - name: Add SSH Key to Known Hosts
        run: |
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "Host ${{ secrets.EC2_HOST }}" >> ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config
          echo "    UserKnownHostsFile ~/.ssh/known_hosts" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: SSH into EC2 and perform tasks
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          GITHUB_BRANCH=${GITHUB_REF##*/}
          ssh -o BatchMode=yes -o ConnectTimeout=10 -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << EOF
            set -e
            cd lms/lms-fe
            git fetch origin
            git reset --hard
            git checkout $GITHUB_BRANCH || git checkout -b $GITHUB_BRANCH origin/$GITHUB_BRANCH
            git reset --hard origin/$GITHUB_BRANCH
            git push dev $GITHUB_BRANCH -f
            exit
          EOF

  notify-slack:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          JOB_STATUS: ${{ needs.build.result }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          ACTOR: ${{ github.actor }}
          WORKFLOW: ${{ github.workflow }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          if [ "$JOB_STATUS" = "success" ]; then
            STATUS_ICON="✅"
            STATUS_TEXT="SUCCESS"
          elif [ "$JOB_STATUS" = "failure" ]; then
            STATUS_ICON="❌"
            STATUS_TEXT="FAILED"
          else
            STATUS_ICON="⚠️"
            STATUS_TEXT="$(echo "$JOB_STATUS" | tr '[:lower:]' '[:upper:]')" # ví dụ: cancelled
          fi

          TEXT="$STATUS_ICON CI/CD $STATUS_TEXT
Repo: $REPO
Branch: $BRANCH
Actor: $ACTOR
Workflow: $WORKFLOW
Run: $RUN_URL"

          payload=$(printf '%s' "$TEXT" | jq -Rs '{text:.}')

          curl -X POST -H --data-urlencode "$payload" \ "$SLACK_WEBHOOK_URL"
